// Auto-generated by app-studio-generator.
//
// Shared `describe(...)` factory for component tests. Each generated
// `AS<X>.test.tsx` invokes this once — the helper opens the describe
// block, builds `baseProps` (testId + label + render-survival style
// stubs), runs the standard "renders with required props" smoke test,
// and forwards control to the per-component `body` callback for the
// family-specific cases.

import React from 'react';
import { render } from '@testing-library/react-native';
import { testDefaults } from '../setup';

export interface ComponentTestBag {
  testId: string;
  label: string;
  textStyle: unknown;
  style: unknown;
}

/**
 * Open a describe block for an AS component test.
 *
 * - `name` becomes the describe title AND seeds `baseProps.testId` as
 *   `<name>-test`.
 * - `renderWithProps` is a closure the smoke test invokes to render
 *   the component. The closure can splice in component-specific
 *   `extraProps` (e.g. `current={testDefaults.today()}` for ASCalendar)
 *   that can't live in `baseProps`.
 * - `body` runs after the smoke and registers any family-specific
 *   `it(...)` cases. Receives `baseProps` so the family cases can spread
 *   it in their own `render(...)` calls.
 */
export function describeComponentContract(
  name: string,
  renderWithProps: (props: ComponentTestBag) => React.ReactElement,
  body?: (baseProps: ComponentTestBag) => void
): void {
  describe(name, () => {
    const baseProps: ComponentTestBag = {
      testId: `${name}-test`,
      label: 'test',
      textStyle: testDefaults.stubStyle(),
      style: testDefaults.stubStyle(),
    };
    it('renders with required props', () => {
      expect(() => render(renderWithProps(baseProps))).not.toThrow();
    });
    body?.(baseProps);
  });
}

/**
 * Variant for components that need a render harness (NavigationContainer
 * etc.) we don't provide in unit tests. Emits a skipped describe with a
 * placeholder so the file still satisfies "must export at least one
 * test" linters.
 */
export function describeComponentContractSkip(name: string): void {
  describe.skip(name, () => {
    it('placeholder', () => {});
  });
}
