// Auto-generated by app-studio-generator.
//
// Shared helpers for workflow-context test files. Each generated
// `<X>Context.test.tsx` invokes these to register the standard tests
// (throws-without-provider) without inlining the same it() body in
// every file.

import { renderHook } from '@testing-library/react-native';

/**
 * Register an `it(...)` that asserts the context hook throws when
 * called outside its Provider. React logs the error before re-throwing,
 * so the helper silences `console.error` for the assertion window.
 */
export function expectHookThrowsWithoutProvider<T>(args: {
  hookName: string;
  providerName: string;
  useHook: () => T;
}): void {
  it(`throws when ${args.hookName}() is used outside ${args.providerName}`, () => {
    const origConsoleError = console.error;
    console.error = () => {};
    try {
      expect(() => renderHook(args.useHook)).toThrow(
        new RegExp(`must be used within an? ${args.providerName}`)
      );
    } finally {
      console.error = origConsoleError;
    }
  });
}
