// Auto-generated by app-studio-generator.
//
// Shared `describe(...)` factory for helper-module service tests. Used
// for services that pull their axios client from `getApiClient()` on a
// helper module instead of via initClients. Setup differs from
// init-clients (jest.mock the helper, retrieve the stub each test),
// and the assertion surface is slimmer (no ctor + no client-not-
// registered guard — class isn't exported, no clientSlot to wipe).

import { MockAxios, assertHappyPath } from './service-test-utils';

export interface HelperModuleServiceContract {
  /** Describe block title — typically the service singleton name. */
  name: string;
  /** Resolved singleton const (not a class). */
  serviceSingleton: unknown;
  /** Public method name on the singleton. */
  methodName: string;
  /** Stub returned by `getApiClient()` — pulled from the helper module's __stub. */
  helperStub: MockAxios;
  /** Axios verb the service calls. */
  httpVerb: 'get' | 'post' | 'put' | 'delete' | 'patch';
  /** Status code the service treats as success (default 200). */
  successStatus?: number;
  /** Method args. */
  params: Record<string, unknown>;
  /** 200 response body. */
  responseData: unknown;
  /** Args expected on the axios call. */
  expectedCall?: unknown[];
  /** Subset matched on the result via toMatchObject. */
  expectedResult?: Record<string, unknown>;
  /** Escape hatch. */
  assertCustom?: (result: unknown) => void;
  /** Regex matched on the exception message. */
  errorPattern?: RegExp;
  /** Skip the 4xx grid test. */
  skip4xxGrid?: boolean;
  /** Skip the null-data test. */
  skipNullData?: boolean;
  /** Skip the empty-payload test. */
  skipEmptyPayload?: boolean;
}

export function describeHelperModuleServiceContract(
  c: HelperModuleServiceContract
): void {
  const successStatus = c.successStatus ?? 200;
  describe(c.name, () => {
    let client: MockAxios;

    beforeEach(() => {
      client = c.helperStub;
      client.get.mockReset();
      client.post.mockReset();
      client.put.mockReset();
      client.delete.mockReset();
      client.patch.mockReset();
    });

    it('exports a singleton instance', () => {
      // Resolved const, not the class. Equality across requires is
      // sufficient for "is a singleton".
      expect(c.serviceSingleton).toBeDefined();
      expect(typeof (c.serviceSingleton as any)[c.methodName]).toBe('function');
    });

    it(`happy path: HTTP ${successStatus} hits expected URL/headers and maps response`, async () => {
      await assertHappyPath({
        client,
        httpVerb: c.httpVerb,
        successStatus,
        responseData: c.responseData,
        expectedCall: c.expectedCall,
        expectedResult: c.expectedResult,
        assertCustom: c.assertCustom,
        invoke: () => (c.serviceSingleton as any)[c.methodName](c.params),
      });
    });

    it('failed response: non-2xx throws', async () => {
      (client as any)[c.httpVerb].mockResolvedValueOnce({
        status: 500,
        data: { error: 'boom' },
      });
      await expect(
        (c.serviceSingleton as any)[c.methodName](c.params)
      ).rejects.toThrow();
    });

    if (!c.skip4xxGrid) {
      it.each([400, 401, 403, 404, 422, 429])(
        'rejects HTTP %i client-error responses',
        async (statusCode) => {
          (client as any)[c.httpVerb].mockResolvedValueOnce({
            status: statusCode,
            data: { error: `rejected-${statusCode}` },
          });
          await expect(
            (c.serviceSingleton as any)[c.methodName](c.params)
          ).rejects.toThrow();
        }
      );
    }

    if (!c.skipNullData) {
      it('handles null response data', async () => {
        (client as any)[c.httpVerb].mockResolvedValueOnce({
          status: successStatus,
          data: null,
        });
        // Service either throws (processJsonPointer hits null on a
        // deeper path) or resolves with undefined-mapped keys (all
        // pointers map to root-level data). Both are valid outcomes.
        try {
          const result = await (c.serviceSingleton as any)[c.methodName](c.params);
          expect(result).toBeDefined();
        } catch (err) {
          expect(err).toBeDefined();
        }
      });
    }

    if (!c.skipEmptyPayload) {
      it(`handles status ${successStatus} with empty response payload`, async () => {
        (client as any)[c.httpVerb].mockResolvedValueOnce({
          status: successStatus,
          data: {},
        });
        try {
          const result = await (c.serviceSingleton as any)[c.methodName](c.params);
          expect(result).toBeDefined();
        } catch (err) {
          expect(err).toBeDefined();
        }
      });
    }

    it('exception path: client rejection bubbles as a service error', async () => {
      (client as any)[c.httpVerb].mockRejectedValueOnce(new Error('network down'));
      const pattern = c.errorPattern ?? new RegExp(`${c.methodName}|${c.name}|failed`, 'i');
      await expect(
        (c.serviceSingleton as any)[c.methodName](c.params)
      ).rejects.toThrow(pattern);
    });
  });
}
