// Auto-generated by app-studio-generator.
//
// Shared `describe(...)` factory for init-clients service tests. Each
// generated `<Service>.test.ts` passes a metadata-only contract; this
// helper produces the 9 standard `it(...)` blocks (singleton, ctor
// guard, happy path, failed, 4xx grid, null data, empty payload,
// exception, client-not-registered guard) from that metadata.
//
// Skip flags + assertCustom callback let services with quirks opt out of
// individual standard tests without leaving the contract.

import { mockClient, MockAxios, assertHappyPath } from './service-test-utils';

export interface InitClientsServiceContract<T> {
  /** Describe block title — typically the service class name. */
  name: string;
  /** The service singleton class (must expose `instance()` + `new()`). */
  ServiceClass: { instance: () => T; new (): T };
  /** Public method name on the singleton (e.g. 'fetchUserProfile1029'). */
  methodName: string;
  /** Key of the AxiosInstance slot in `initClients({...})` arg. */
  clientKey: string;
  /** Internal field set to `undefined` to simulate "forgot initClients". */
  clientSlot: string;
  /** Extra clientKey/slot pairs when the service uses multiple clients. */
  extraClients?: Array<{ clientKey: string; clientSlot: string }>;
  /** Axios verb the service calls on the happy path. */
  httpVerb: 'get' | 'post' | 'put' | 'delete' | 'patch';
  /** Status code the service treats as success (default 200). */
  successStatus?: number;
  /** Method args. */
  params: Record<string, unknown>;
  /** 200 response body — primitives at every JSON pointer the service reads. */
  responseData: unknown;
  /**
   * Args expected on the axios call: `[url, body?, optionsObject]`.
   * Each entry is matched via `expect.toHaveBeenCalledWith(...)`.
   */
  expectedCall?: unknown[];
  /**
   * Subset of the result the happy-path test should match (via
   * `toMatchObject`). Use `assertCustom` for anything more complex.
   */
  expectedResult?: Record<string, unknown>;
  /** Escape hatch for assertions outside the declarative shape. */
  assertCustom?: (result: unknown) => void;
  /** Regex matched on the exception message (defaults to a permissive match). */
  errorPattern?: RegExp;
  /** Skip the 4xx grid test (some services don't return 4xx). */
  skip4xxGrid?: boolean;
  /** Skip the null-data test (some services accept null). */
  skipNullData?: boolean;
  /** Skip the empty-payload test. */
  skipEmptyPayload?: boolean;
}

export function describeInitClientsServiceContract<T>(
  c: InitClientsServiceContract<T>
): void {
  const successStatus = c.successStatus ?? 200;
  describe(c.name, () => {
    let client: MockAxios;

    beforeEach(() => {
      client = mockClient();
      const service = c.ServiceClass.instance() as any;
      const clients: Record<string, unknown> = {
        [c.clientKey]: client as unknown as any,
      };
      (c.extraClients ?? []).forEach((e) => {
        clients[e.clientKey] = client as unknown as any;
      });
      service.initClients(clients);
    });

    it('exposes a singleton via instance()', () => {
      const a = c.ServiceClass.instance();
      const b = c.ServiceClass.instance();
      expect(a).toBe(b);
    });

    it('throws if direct constructor is invoked', () => {
      // The generated class blocks `new X()` once the singleton exists.
      const Ctor = c.ServiceClass as unknown as new () => unknown;
      expect(() => new Ctor()).toThrow();
    });

    it(`happy path: HTTP ${successStatus} hits expected URL/headers and maps response`, async () => {
      await assertHappyPath({
        client,
        httpVerb: c.httpVerb,
        successStatus,
        responseData: c.responseData,
        expectedCall: c.expectedCall,
        expectedResult: c.expectedResult,
        assertCustom: c.assertCustom,
        invoke: () =>
          (c.ServiceClass.instance() as any)[c.methodName](c.params),
      });
    });

    it('failed response: non-2xx throws', async () => {
      (client as any)[c.httpVerb].mockResolvedValueOnce({
        status: 500,
        data: { error: 'boom' },
      });
      const service = c.ServiceClass.instance() as any;
      await expect(service[c.methodName](c.params)).rejects.toThrow();
    });

    if (!c.skip4xxGrid) {
      it.each([400, 401, 403, 404, 422, 429])(
        'rejects HTTP %i client-error responses',
        async (statusCode) => {
          (client as any)[c.httpVerb].mockResolvedValueOnce({
            status: statusCode,
            data: { error: `rejected-${statusCode}` },
          });
          const service = c.ServiceClass.instance() as any;
          await expect(service[c.methodName](c.params)).rejects.toThrow();
        }
      );
    }

    if (!c.skipNullData) {
      it('handles null response data', async () => {
        (client as any)[c.httpVerb].mockResolvedValueOnce({
          status: successStatus,
          data: null,
        });
        // Service either throws (processJsonPointer hits null on a
        // deeper path) or resolves with undefined-mapped keys (all
        // pointers map to root-level data). Both are valid outcomes —
        // we just need to confirm the service doesn't hang.
        try {
          const service = c.ServiceClass.instance() as any;
          const result = await service[c.methodName](c.params);
          expect(result).toBeDefined();
        } catch (err) {
          expect(err).toBeDefined();
        }
      });
    }

    if (!c.skipEmptyPayload) {
      it(`handles status ${successStatus} with empty response payload`, async () => {
        (client as any)[c.httpVerb].mockResolvedValueOnce({
          status: successStatus,
          data: {},
        });
        // Service either resolves (pointers map to undefined) or rejects
        // (inner gate requires a specific pointer). Both are valid.
        try {
          const service = c.ServiceClass.instance() as any;
          const result = await service[c.methodName](c.params);
          expect(result).toBeDefined();
        } catch (err) {
          expect(err).toBeDefined();
        }
      });
    }

    it('exception path: client rejection bubbles as a service error', async () => {
      (client as any)[c.httpVerb].mockRejectedValueOnce(new Error('network down'));
      const service = c.ServiceClass.instance() as any;
      const pattern = c.errorPattern ?? new RegExp(`${c.methodName}|${c.name}|failed`, 'i');
      await expect(service[c.methodName](c.params)).rejects.toThrow(pattern);
    });

    it('client-not-registered guard fires when initClients was skipped', async () => {
      // Wipe the registered client slot to simulate the production
      // "forgot initClients" footgun. The service wraps errors several
      // times so we assert on `not.toHaveBeenCalled` for the HTTP mock
      // rather than the error message.
      const service = c.ServiceClass.instance() as unknown as Record<string, unknown>;
      service[c.clientSlot] = undefined;
      (c.extraClients ?? []).forEach((e) => {
        service[e.clientSlot] = undefined;
      });
      await expect(
        (c.ServiceClass.instance() as any)[c.methodName](c.params)
      ).rejects.toThrow();
      expect((client as any)[c.httpVerb]).not.toHaveBeenCalled();
    });
  });
}
