// Auto-generated by app-studio-generator.
//
// Shared service-test scaffolding. Each <Service>.test.ts imports from
// here so the AxiosInstance stand-in is defined once per project
// instead of duplicated per service file (SonarQube duplicate-code).

export type HttpFn = jest.Mock<
  Promise<{ status: number; data: unknown }>,
  any[]
>;

export interface MockAxios {
  get: HttpFn;
  post: HttpFn;
  put: HttpFn;
  delete: HttpFn;
  patch: HttpFn;
}

// Minimal AxiosInstance stand-in. The service only ever calls one
// verb per request branch — the others are present so the type
// satisfies `AxiosInstance` without pulling in axios at test time.
export const mockClient = (): MockAxios => ({
  get: jest.fn(),
  post: jest.fn(),
  put: jest.fn(),
  delete: jest.fn(),
  patch: jest.fn(),
});

/**
 * Builds the mock module exposed via `jest.mock(<helperPath>, () => …)`
 * for helper-module-shape services. Each such test used to inline the
 * factory body — 14+ identical lines per file, which SonarQube flagged
 * as cross-file duplication. Routing the factory through this helper
 * keeps the duplicated region down to a one-line `require()` call.
 *
 * NOTE: must be called *inside* the jest.mock factory (via `require`),
 * because jest hoists `jest.mock` above any `import` statement and the
 * factory closure can only reference variables prefixed with `mock*`.
 */
export const buildHelperModuleMock = (specifier: string) => {
  const get = jest.fn();
  const post = jest.fn();
  const put = jest.fn();
  const del = jest.fn();
  const patch = jest.fn();
  const stub = { get, post, put, delete: del, patch };
  return {
    [specifier]: { getApiClient: () => stub },
    __stub: stub,
  };
};

/**
 * Shared happy-path assertions used by both service contracts. Each
 * contract resolves the singleton differently (init-clients reads
 * `ServiceClass.instance()`, helper-module reads a captured const) so the
 * call site passes the already-resolved result via the `invoke` callback,
 * and this helper owns the mock setup + assertion shape.
 */
export async function assertHappyPath(opts: {
  client: MockAxios;
  httpVerb: 'get' | 'post' | 'put' | 'delete' | 'patch';
  successStatus: number;
  responseData: unknown;
  expectedCall?: unknown[];
  expectedResult?: Record<string, unknown>;
  assertCustom?: (result: unknown) => void;
  invoke: () => Promise<unknown>;
}): Promise<void> {
  (opts.client as any)[opts.httpVerb].mockResolvedValueOnce({
    status: opts.successStatus,
    data: opts.responseData,
  });
  const result = await opts.invoke();
  expect((opts.client as any)[opts.httpVerb]).toHaveBeenCalledTimes(1);
  if (opts.expectedCall) {
    expect((opts.client as any)[opts.httpVerb]).toHaveBeenCalledWith(
      ...(opts.expectedCall as [unknown, ...unknown[]])
    );
  }
  if (opts.expectedResult) {
    expect(result).toMatchObject(opts.expectedResult);
  }
  opts.assertCustom?.(result);
}
