import React from 'react';
import { StyleProp } from 'react-native';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASButton } from '@/components';

type Props = React.ComponentProps<typeof ASButton> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASButton.
 *
 * Applies the structural props that are constant across every ASButton
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASButton directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppButton: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASButton
    iconPosition={'leading'}
    simpleTextButton={false}
    backgroundImageResizeMode={'contain'}
    trailingIconStyles={sharedStyles.analyticsCtaActionButtonTrailingIconStyles}
    leadingIconStyles={sharedStyles.analyticsCtaActionButtonLeadingIconStyles}
    iconStyles={sharedStyles.analyticsCtaActionButtonIconStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppButton;
