import React from 'react';
import { StyleProp } from 'react-native';
import { ASListView } from '@/components';

type Props = React.ComponentProps<typeof ASListView> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASListView.
 *
 * Applies the structural props that are constant across every ASListView
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASListView directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppListView: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASListView
    itemSpacing={12}
    orientation={'vertical'}
    showsHorizontalScrollIndicator={false}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppListView;
