import React from 'react';
import { StyleProp } from 'react-native';
import { text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASListTile } from '@/components';

type Props = React.ComponentProps<typeof ASListTile> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASListTile.
 *
 * Applies the structural props that are constant across every ASListTile
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASListTile directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppListTile: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASListTile
    subtitle={''}
    trailingIcon={'chevron_right'}
    trailingIconStyles={sharedStyles.analyticsItemListItemTrailingIconStyles}
    leadingIconStyles={sharedStyles.analyticsItemListItemLeadingIconStyles}
    subTitleStyle={[
      text.body.small,
      sharedStyles.analyticsItemListItemSubTitle,
    ]}
    titleStyles={[
      text.label.medium,
      sharedStyles.analyticsItemListItemSubTitle,
    ]}
    containerStyle={sharedStyles.analyticsItemListItemContainer}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppListTile;
