import React from 'react';
import { StyleProp } from 'react-native';
import { color, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASPasswordTextField } from '@/components';

type Props = React.ComponentProps<typeof ASPasswordTextField> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASPasswordTextField.
 *
 * Applies the structural props that are constant across every ASPasswordTextField
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASPasswordTextField directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppPasswordTextField: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASPasswordTextField
    placeholderTextColor={color.text.tertiary}
    borderErrorColor={color.status.danger}
    borderActiveColor={color.brand.primary}
    secureTextEntry={true}
    autoComplete={'off'}
    autoCapitalize={'none'}
    isShowSuffixIcon={true}
    keyboardType={'default'}
    allowFontScaling={false}
    inputTextStyle={[
      text.body.medium,
      sharedStyles.createRecepientInput2InputText,
    ]}
    placeholderTextStyle={sharedStyles.createRecepientInput2PlaceholderText}
    labelTextStyle={[
      text.label.medium,
      sharedStyles.createQuoteContainerBackgroundBorderDropDown2LabelText,
    ]}
    errorMessageTextStyle={sharedStyles.createRecepientInput2ErrorMessageText}
    contentContainerStyle={sharedStyles.createRecepientInput2ContentContainer}
    suffixIconStyles={sharedStyles.loginInputSuffixIconStyles}
    prefixTextStyle={[
      text.body.medium,
      sharedStyles.createQuoteContainerBackgroundBorderDropDown2DropdownTextStyles,
    ]}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppPasswordTextField;
