import React from 'react';
import { StyleProp } from 'react-native';
import { ASStack } from '@/components';

type Props = React.ComponentProps<typeof ASStack> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASStack.
 *
 * Applies the structural props that are constant across every ASStack
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASStack directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppStack: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASStack
    backgroundImageResizeMode={'contain'}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppStack;
