// Auto-generated by app-studio-generator.
//
// AppProviders smoke test — composes the context tree via reduceRight.
// Under the workflow-context mock the providers are no-op wrappers, so
// the assertion is just that children render.

import React from 'react';
import { render } from '@testing-library/react-native';
import { Text } from 'react-native';
import { AppProviders } from '../../src/providers/AppProviders';

describe('AppProviders', () => {
  it('renders children without throwing', () => {
    expect(() =>
      render(
        <AppProviders>
          <Text testID="child">child-renders</Text>
        </AppProviders>,
      ),
    ).not.toThrow();
  });

  it('the rendered tree includes the child node', () => {
    const { getByTestId } = render(
      <AppProviders>
        <Text testID="appproviders-child">hello</Text>
      </AppProviders>,
    );
    expect(getByTestId('appproviders-child')).toBeOnTheScreen();
  });
});
