// Auto-generated by app-studio-generator.
//
// as.jsonata.functions tests — empty-expression guard, compile +
// register + evaluate pipeline, `$uuid()` v4 shape.
//
// The `jsonata` library has ESM/CJS interop friction under Jest; mock
// it with a minimal API surface so the wrapper logic runs without the
// real resolver. Bypass the global stub via the `@real/` prefix.

// Capture the constructor + per-expr stubs so each test can drive them.
jest.mock('jsonata', () => {
  const fn = jest.fn((expression: string) => {
    const registered: Record<string, (...args: unknown[]) => unknown> = {};
    return {
      __expression: expression,
      registerFunction: jest.fn(
        (name: string, impl: (...args: unknown[]) => unknown) => {
          registered[name] = impl;
        },
      ),
      evaluate: jest.fn(async (_data: unknown) => {
        // Default behaviour for simple assertions — invoke the registered
        // `$uuid()` if the expression is exactly that, else return the
        // expression-string back so tests can assert it was evaluated.
        if (expression === '$uuid()' && registered.uuid) {
          return registered.uuid();
        }
        return `evaluated:${expression}`;
      }),
      __registered: registered,
    };
  });
  return { __esModule: true, default: fn };
});

// eslint-disable-next-line @typescript-eslint/no-var-requires
const jsonataMod: any = require('jsonata');
const jsonataMockFactory: jest.Mock = jsonataMod.default;

import {
  evaluateASJsonata,
  registerASFunctions,
} from '@real/utils/as.jsonata.functions';

const UUID_V4_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

beforeEach(() => {
  jsonataMockFactory.mockClear();
});

describe('as.jsonata.functions — evaluateASJsonata guard', () => {
  it('throws when the expression is empty string', async () => {
    await expect(evaluateASJsonata('', {})).rejects.toThrow(
      /must not be empty/i,
    );
    // The guard fires BEFORE invoking jsonata — the constructor should
    // not have been called.
    expect(jsonataMockFactory).not.toHaveBeenCalled();
  });

  it('throws when the expression is undefined-coerced empty', async () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await expect(evaluateASJsonata(undefined as any, {})).rejects.toThrow(
      /must not be empty/i,
    );
  });
});

describe('as.jsonata.functions — evaluateASJsonata pipeline', () => {
  it('compiles the expression with jsonata() and evaluates the data context', async () => {
    const result = await evaluateASJsonata('user.name', { user: { name: 'Alice' } });
    expect(jsonataMockFactory).toHaveBeenCalledWith('user.name');
    expect(result).toBe('evaluated:user.name');
  });

  it('registers $uuid() before evaluating', async () => {
    await evaluateASJsonata('$uuid()', {});
    // The returned $uuid value should look like a v4 UUID.
    const fakeExpr = jsonataMockFactory.mock.results[0].value;
    expect(fakeExpr.registerFunction).toHaveBeenCalledWith(
      'uuid',
      expect.any(Function),
      '<:s>',
    );
  });

  it('uses the registered $uuid() to produce a v4-shaped string', async () => {
    const out = (await evaluateASJsonata('$uuid()', {})) as string;
    expect(typeof out).toBe('string');
    expect(out).toMatch(UUID_V4_RE);
  });

  it('wraps thrown errors from jsonata with "JSONata evaluation failed:" prefix', async () => {
    jsonataMockFactory.mockImplementationOnce(() => {
      throw new Error('compile blew up');
    });
    await expect(evaluateASJsonata('whatever', {})).rejects.toThrow(
      /JSONata evaluation failed: compile blew up/,
    );
  });

  it('wraps non-Error thrown values with "JSONata evaluation failed:" prefix', async () => {
    jsonataMockFactory.mockImplementationOnce(() => {
      // eslint-disable-next-line no-throw-literal
      throw 'string-thrown';
    });
    await expect(evaluateASJsonata('whatever', {})).rejects.toThrow(
      /JSONata evaluation failed: string-thrown/,
    );
  });
});

describe('as.jsonata.functions — registerASFunctions', () => {
  it('registers uuid on the passed expression with the "<:s>" signature', () => {
    const fakeExpr = (jsonataMockFactory as any)('$uuid()');
    registerASFunctions(fakeExpr);
    expect(fakeExpr.registerFunction).toHaveBeenCalledWith(
      'uuid',
      expect.any(Function),
      '<:s>',
    );
  });

  it('the registered uuid() returns a v4-shaped string', () => {
    const fakeExpr = (jsonataMockFactory as any)('$uuid()');
    registerASFunctions(fakeExpr);
    // Invoke the registered fn — it's the second arg to the call.
    const uuidImpl = (fakeExpr.registerFunction as jest.Mock).mock.calls[0][1];
    const out = uuidImpl();
    expect(typeof out).toBe('string');
    expect(out).toMatch(UUID_V4_RE);
  });
});
