// Auto-generated by app-studio-generator.
//
// common.utils tests — pure functions, input/output assertions.

import { Platform } from 'react-native';
import { renderHook, act } from '@testing-library/react-native';
import {
  screenWidth,
  screenHeight,
  convertPercentageToPx,
  isAndroid,
  getLoadingStatus,
  hexToRgbaWithOpacity,
  toNumber,
  useIsTimeoutLoading,
  getPlatformShadowStyle,
  resolveEffectShadowToken,
  parseColorToRgba,
} from '../../src/utils/common.utils';

// The mocked Dimensions in RN's jest preset returns 750x1334 for
// 'window'. Re-derive these constants to avoid coupling the test to a
// specific stubbed value — just confirm they're finite positive numbers.
describe('common.utils — screen size exports', () => {
  it('exposes finite, positive screenWidth / screenHeight', () => {
    expect(typeof screenWidth).toBe('number');
    expect(typeof screenHeight).toBe('number');
    expect(Number.isFinite(screenWidth)).toBe(true);
    expect(Number.isFinite(screenHeight)).toBe(true);
    expect(screenWidth).toBeGreaterThan(0);
    expect(screenHeight).toBeGreaterThan(0);
  });
});

describe('common.utils — isAndroid', () => {
  it('matches Platform.OS at module-load time', () => {
    // The constant is captured at module-load — we just check it's
    // consistent with whatever Platform.OS is in the test env.
    expect(isAndroid).toBe(Platform.OS === 'android');
    expect(typeof isAndroid).toBe('boolean');
  });
});

describe('common.utils — convertPercentageToPx', () => {
  it('returns undefined for falsy input', () => {
    expect(convertPercentageToPx(undefined, true)).toBeUndefined();
    expect(convertPercentageToPx(0, true)).toBeUndefined();
    expect(convertPercentageToPx('', false)).toBeUndefined();
  });

  it('returns the number as-is when input is numeric', () => {
    expect(convertPercentageToPx(42, true)).toBe(42);
    expect(convertPercentageToPx(100, false)).toBe(100);
  });

  it('converts a percentage string against screen width when isWidth=true', () => {
    const result = convertPercentageToPx('50%', true);
    expect(typeof result).toBe('number');
    // 50% of finite screenWidth → finite number > 0
    expect(Number.isFinite(result)).toBe(true);
    expect((result as number) * 2).toBeCloseTo(screenWidth, 0);
  });

  it('converts against screen height when isWidth=false', () => {
    const result = convertPercentageToPx('50%', false);
    expect((result as number) * 2).toBeCloseTo(screenHeight, 0);
  });
});

describe('common.utils — getLoadingStatus', () => {
  it('returns false for falsy input', () => {
    expect(getLoadingStatus(undefined)).toBe(false);
    expect(getLoadingStatus(false)).toBe(false);
  });

  it('returns true when a single boolean is true', () => {
    expect(getLoadingStatus(true)).toBe(true);
  });

  it('returns true when ANY array element is true', () => {
    expect(getLoadingStatus([false, false, true])).toBe(true);
    expect(getLoadingStatus([true, false])).toBe(true);
  });

  it('returns false when EVERY array element is false', () => {
    expect(getLoadingStatus([false, false, false])).toBe(false);
  });
});

describe('common.utils — hexToRgbaWithOpacity', () => {
  it('returns the white fallback when hex is undefined', () => {
    expect(hexToRgbaWithOpacity(undefined)).toBe('#fff');
  });

  it('parses a 6-digit hex without the leading #', () => {
    expect(hexToRgbaWithOpacity('ff0000')).toBe('rgba(255, 0, 0, 0.2)');
  });

  it('strips the leading # before parsing', () => {
    expect(hexToRgbaWithOpacity('#00ff00', 0.5)).toBe('rgba(0, 255, 0, 0.5)');
  });

  it('expands a 3-digit shorthand hex', () => {
    expect(hexToRgbaWithOpacity('#f00')).toBe('rgba(255, 0, 0, 0.2)');
  });

  it('respects the opacity argument', () => {
    expect(hexToRgbaWithOpacity('#0000ff', 0.75)).toBe(
      'rgba(0, 0, 255, 0.75)',
    );
  });
});

describe('common.utils — toNumber', () => {
  it('returns the number as-is', () => {
    expect(toNumber(42)).toBe(42);
    expect(toNumber(3.14)).toBe(3.14);
  });

  it('parses a numeric string', () => {
    expect(toNumber('42')).toBe(42);
    expect(toNumber('3.14')).toBe(3.14);
  });

  it('returns 0 for non-numeric strings', () => {
    expect(toNumber('abc')).toBe(0);
    expect(toNumber('')).toBe(0);
    expect(toNumber(null)).toBe(0);
    expect(toNumber(undefined)).toBe(0);
  });
});

describe('common.utils — parseColorToRgba', () => {
  it('parses an `rgb()` string and applies the opacity', () => {
    expect(parseColorToRgba('rgb(10, 20, 30)', 0.5)).toBe(
      'rgba(10, 20, 30, 0.5)',
    );
  });

  it('combines existing alpha with new opacity for `rgba()` input', () => {
    // existing alpha 0.5, new opacity 0.5 → 0.25 combined
    expect(parseColorToRgba('rgba(10, 20, 30, 0.5)', 0.5)).toBe(
      'rgba(10, 20, 30, 0.25)',
    );
  });

  it('parses a 3-digit hex', () => {
    expect(parseColorToRgba('#abc', 1)).toMatch(/^rgba\(170, 187, 204, 1\)$/);
  });

  it('parses a 6-digit hex', () => {
    expect(parseColorToRgba('#ff0080', 1)).toBe('rgba(255, 0, 128, 1)');
  });

  it('parses an 8-digit hex and combines its alpha with the opacity', () => {
    // 8-digit hex `#ff008080` — alpha byte 0x80 ≈ 0.502
    const out = parseColorToRgba('#ff008080', 1);
    expect(out).toMatch(/^rgba\(255, 0, 128, 0\.5\d*\)$/);
  });

  it('clamps opacity >= 1 to 1', () => {
    expect(parseColorToRgba('#000000', 5)).toBe('rgba(0, 0, 0, 1)');
  });

  it('pads short hex to 6 digits', () => {
    // '#a' (length 1) → padded to 'a00000' → rgb(160, 0, 0)
    const out = parseColorToRgba('#a', 1);
    expect(out).toBe('rgba(160, 0, 0, 1)');
  });
});

describe('common.utils — getPlatformShadowStyle', () => {
  const originalOS = Platform.OS;
  afterEach(() => {
    Object.defineProperty(Platform, 'OS', { get: () => originalOS });
  });

  it('returns {} when input is null / undefined', () => {
    expect(getPlatformShadowStyle(null)).toEqual({});
    expect(getPlatformShadowStyle(undefined)).toEqual({});
  });

  it('returns {} when no shadow property is set', () => {
    expect(getPlatformShadowStyle({})).toEqual({});
  });

  it('emits boxShadow on web/android', () => {
    Object.defineProperty(Platform, 'OS', { get: () => 'android' });
    const out = getPlatformShadowStyle({
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      shadowOpacity: 0.5,
    });
    expect(out).toHaveProperty('boxShadow');
    expect((out as { boxShadow: string }).boxShadow).toMatch(/0px 2px 4px/);
  });

  it('emits iOS shadow* properties on ios', () => {
    Object.defineProperty(Platform, 'OS', { get: () => 'ios' });
    const out = getPlatformShadowStyle({
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      shadowOpacity: 0.5,
    });
    expect(out).toHaveProperty('shadowOpacity', 1);
    expect(out).toHaveProperty('shadowOffset');
    expect(out).toHaveProperty('shadowRadius', 4);
    expect(out).toHaveProperty('shadowColor');
  });
});

describe('common.utils — resolveEffectShadowToken', () => {
  it('merges token + overrides and delegates to getPlatformShadowStyle', () => {
    const out = resolveEffectShadowToken(
      { color: '#000', blur: 2, xOffset: 0, yOffset: 1, spread: 0 },
      { blur: 8 },
    );
    // Whatever the platform, the function returns an object — exact
    // contents differ by Platform.OS, just verify it's not the empty
    // result that getPlatformShadowStyle returns for null input.
    expect(out).toBeDefined();
    expect(typeof out).toBe('object');
  });

  it('uses fallback defaults when token + overrides leave keys undefined', () => {
    // blur=0, color='', spread=0 — falsy fallbacks kick in
    const out = resolveEffectShadowToken({});
    expect(out).toBeDefined();
  });
});

describe('common.utils — useIsTimeoutLoading hook', () => {
  beforeEach(() => {
    jest.useFakeTimers();
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  it('starts as false', () => {
    const { result } = renderHook(() => useIsTimeoutLoading(1000, false));
    expect(result.current).toBe(false);
  });

  it('flips to true after the timeout when loading=true', () => {
    const { result } = renderHook(() => useIsTimeoutLoading(1000, true));
    expect(result.current).toBe(false);
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      jest.advanceTimersByTime(1001);
    });
    expect(result.current).toBe(true);
  });

  it('clears the timeout when unmounted', () => {
    const { result, unmount } = renderHook(() =>
      useIsTimeoutLoading(1000, true),
    );
    expect(result.current).toBe(false);
    unmount();
    // After unmount the cleanup runs — advancing the clock shouldn't
    // throw or change anything observable. Just confirm no crash.
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      jest.advanceTimersByTime(5000);
    });
    expect(result.current).toBe(false);
  });

  it('does not arm the timer when loading=false', () => {
    const { result } = renderHook(() => useIsTimeoutLoading(1000, false));
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      jest.advanceTimersByTime(5000);
    });
    expect(result.current).toBe(false);
  });
});
