// Auto-generated by app-studio-generator.
//
// secureStorage tests — delegates to react-native-keychain on native,
// falls back to localStorage on web. Regressions risk leaking
// credentials to the wrong storage.

jest.unmock('../../src/utils/secureStorage');

// Default platform = ios. Individual web tests override via the Platform mock.
let mockPlatformOS: 'ios' | 'android' | 'web' = 'ios';
jest.mock('react-native', () => ({
  Platform: {
    get OS() { return mockPlatformOS; },
  },
}));

const mockSetGenericPassword = jest.fn();
const mockGetGenericPassword = jest.fn();
const mockResetGenericPassword = jest.fn();
jest.mock('react-native-keychain', () => ({
  setGenericPassword: (...args: any[]) => mockSetGenericPassword(...args),
  getGenericPassword: (...args: any[]) => mockGetGenericPassword(...args),
  resetGenericPassword: (...args: any[]) => mockResetGenericPassword(...args),
}));

import {
  setKeychainData,
  keychainData,
  removeKeychainData,
} from '../../src/utils/secureStorage';

describe('secureStorage', () => {
  beforeEach(() => {
    mockSetGenericPassword.mockReset();
    mockGetGenericPassword.mockReset();
    mockResetGenericPassword.mockReset();
    mockPlatformOS = 'ios';
    // Web fallback uses window.localStorage; wipe it for determinism.
    if (typeof window !== 'undefined' && window.localStorage) {
      window.localStorage.clear();
    }
  });

  describe('setKeychainData', () => {
    it('persists via Keychain on native and returns true', async () => {
      mockSetGenericPassword.mockResolvedValueOnce(true);
      const ok = await setKeychainData('accessToken', 'abc');
      expect(ok).toBe(true);
      expect(mockSetGenericPassword).toHaveBeenCalledWith('accessToken', 'abc', { service: 'accessToken' });
    });

    it('falls back to localStorage on web platform', async () => {
      mockPlatformOS = 'web';
      const ok = await setKeychainData('accessToken', 'abc');
      expect(ok).toBe(true);
      expect(mockSetGenericPassword).not.toHaveBeenCalled();
      // Web fallback only runs when window.localStorage exists in the
      // JSDOM environment; if it isn't present we still expect `true`
      // from the early return (sets nothing).
      if (typeof window !== 'undefined' && window.localStorage) {
        expect(window.localStorage.getItem('accessToken')).toBe('abc');
      }
    });

    it('returns false when Keychain throws', async () => {
      mockSetGenericPassword.mockRejectedValueOnce(new Error('keystore locked'));
      const ok = await setKeychainData('accessToken', 'abc');
      expect(ok).toBe(false);
    });
  });

  describe('keychainData', () => {
    it('reads value from Keychain on native', async () => {
      mockGetGenericPassword.mockResolvedValueOnce({ username: 'accessToken', password: 'abc' });
      const value = await keychainData('accessToken');
      expect(mockGetGenericPassword).toHaveBeenCalled();
      // Wrapper returns the password (the actual token), not the wrapper object.
      expect(value).toBe('abc');
    });

    it('returns undefined when nothing is stored', async () => {
      mockGetGenericPassword.mockResolvedValueOnce(false);
      const value = await keychainData('accessToken');
      // Generated wrapper returns null/undefined for "not found" — accept either.
      expect(value === null || value === undefined).toBe(true);
    });
  });

  describe('removeKeychainData', () => {
    it('resets the Keychain entry on native', async () => {
      mockResetGenericPassword.mockResolvedValueOnce(true);
      await removeKeychainData('accessToken');
      expect(mockResetGenericPassword).toHaveBeenCalled();
    });
  });
});
