// Auto-generated by app-studio-generator.
//
// NavigationService tests — asserts navigate/goBack/popToTop delegate
// to navigationRef.current.

jest.mock('@react-navigation/native', () => ({
  // We only need StackActions.popToTop for this file — return a stable
  // action object so the assertion can check identity.
  StackActions: {
    popToTop: jest.fn(() => ({ type: 'POP_TO_TOP_ACTION' })),
  },
  // createNavigationContainerRef would normally come from the lib —
  // NavigationService uses React.createRef() directly so we don't need it.
}));

import NavigationService, {
  navigationRef,
} from '../../src/navigation/NavigationService';

describe('NavigationService', () => {
  let mockCurrent: {
    navigate: jest.Mock;
    goBack: jest.Mock;
    dispatch: jest.Mock;
  };

  beforeEach(() => {
    mockCurrent = {
      navigate: jest.fn(),
      goBack: jest.fn(),
      dispatch: jest.fn(),
    };
    // React.createRef returns { current: T | null }. Tests override
    // `current` directly to simulate "navigation container has mounted".
    (navigationRef as { current: unknown }).current = mockCurrent;
  });

  afterEach(() => {
    (navigationRef as { current: unknown }).current = null;
  });

  it('exports a singleton instance', () => {
    expect(NavigationService).toBeDefined();
    expect(typeof NavigationService.navigate).toBe('function');
    expect(typeof NavigationService.goBack).toBe('function');
    expect(typeof NavigationService.popToTop).toBe('function');
  });

  it('navigate() forwards routeName + params to the ref', () => {
    NavigationService.navigate('Home', { tab: 'wallet' });
    expect(mockCurrent.navigate).toHaveBeenCalledWith('Home', {
      tab: 'wallet',
    });
  });

  it('navigate() works with only a routeName (params optional)', () => {
    NavigationService.navigate('Settings');
    expect(mockCurrent.navigate).toHaveBeenCalledWith('Settings', undefined);
  });

  it('goBack() invokes ref.goBack', () => {
    NavigationService.goBack();
    expect(mockCurrent.goBack).toHaveBeenCalledTimes(1);
  });

  it('popToTop() dispatches the StackActions.popToTop action', () => {
    NavigationService.popToTop();
    expect(mockCurrent.dispatch).toHaveBeenCalledTimes(1);
    expect(mockCurrent.dispatch).toHaveBeenCalledWith({
      type: 'POP_TO_TOP_ACTION',
    });
  });

  it('navigate() is a no-op (no throw) when the ref is not mounted', () => {
    (navigationRef as { current: unknown }).current = null;
    expect(() => NavigationService.navigate('AnyRoute', {})).not.toThrow();
  });

  it('goBack() is a no-op when the ref is not mounted', () => {
    (navigationRef as { current: unknown }).current = null;
    expect(() => NavigationService.goBack()).not.toThrow();
  });

  it('popToTop() is a no-op when the ref is not mounted', () => {
    (navigationRef as { current: unknown }).current = null;
    expect(() => NavigationService.popToTop()).not.toThrow();
  });
});
