// Auto-generated by app-studio-generator.
//
// AuthorizationClient orchestrator tests — singleton, configure
// delegation, getConfigs guard, session-listener wiring.

import { DeviceEventEmitter } from 'react-native';

// Some apps' generated `api-clients/index.tsx` imports a `Service` base
// from `../Service` that the code generator doesn't emit. Virtual mock
// so the import resolves and `Service.configure(...)` doesn't crash.
jest.mock(
  '../../src/services/Service',
  () => ({ Service: { configure: jest.fn() } }),
  { virtual: true }
);

// authApiClient is the resolved singleton const exported from AuthApiClient.tsx.
// Mock the module so `.configure` is a jest.fn we can assert against — and
// re-export `__mockConfigure` so the test can drive it.
jest.mock('../../src/services/api-clients/AuthApiClient', () => {
  const mockConfigure = jest.fn();
  return {
    authApiClient: { configure: mockConfigure },
    __mockConfigure: mockConfigure,
  };
});
// eslint-disable-next-line @typescript-eslint/no-var-requires
const authApiClientMod: any = require('../../src/services/api-clients/AuthApiClient');
const authApiClientConfigure: jest.Mock = authApiClientMod.__mockConfigure;


import { AuthorizationClient } from '../../src/services/api-clients';

const validConfigs = {
  appId: 'test-app',
  envId: 'test-env',
  bankId: 'test-bank',
  apiBaseUrl: 'https://api.example.test',
  authBaseUrl: 'https://auth.example.test',
};

describe('AuthorizationClient', () => {
  beforeEach(() => {
    authApiClientConfigure.mockReset();
    // Reset the cached configs on the singleton so each test starts
    // from "not configured yet".
    (AuthorizationClient.instance() as unknown as { _configs?: unknown })._configs = undefined;
  });

  it('exposes a singleton via instance()', () => {
    const a = AuthorizationClient.instance();
    const b = AuthorizationClient.instance();
    expect(a).toBe(b);
  });

  it('throws if direct constructor is invoked', () => {
    const Ctor = AuthorizationClient as unknown as new () => unknown;
    expect(() => new Ctor()).toThrow(/instance\(\) instead of new/i);
  });

  it('configure() resolves after delegating to authApiClient.configure', async () => {
    await AuthorizationClient.instance().configure(validConfigs);
    expect(authApiClientConfigure).toHaveBeenCalledTimes(1);
    expect(authApiClientConfigure).toHaveBeenCalledWith(validConfigs);
  });


  it('getConfigs() throws before configure() has been called', () => {
    expect(() => AuthorizationClient.instance().getConfigs()).toThrow(
      /must be configured/i,
    );
  });

  it('getConfigs() returns the stored configs after configure()', async () => {
    await AuthorizationClient.instance().configure(validConfigs);
    expect(AuthorizationClient.instance().getConfigs()).toEqual(validConfigs);
  });

  it('addSessionListener wires to DeviceEventEmitter for "authcomponent.session.expired"', () => {
    const spy = jest.spyOn(DeviceEventEmitter, 'addListener');
    const listener = jest.fn();
    AuthorizationClient.instance().addSessionListener(listener);
    expect(spy).toHaveBeenCalledWith(
      'authcomponent.session.expired',
      listener,
    );
    spy.mockRestore();
  });

  it('removeSessionListener wires to DeviceEventEmitter.removeListener', () => {
    // `removeListener` was deprecated then dropped from RN's EventEmitter
    // surface, so the jest preset's DeviceEventEmitter may not expose it.
    // Patch a jest.fn() onto the slot directly, then restore.
    const original = (DeviceEventEmitter as unknown as { removeListener?: unknown })
      .removeListener;
    const stub = jest.fn();
    (DeviceEventEmitter as unknown as { removeListener: unknown }).removeListener =
      stub;
    try {
      const listener = jest.fn();
      AuthorizationClient.instance().removeSessionListener(listener);
      expect(stub).toHaveBeenCalledWith(
        'authcomponent.session.expired',
        listener,
      );
    } finally {
      if (original === undefined) {
        delete (DeviceEventEmitter as unknown as { removeListener?: unknown })
          .removeListener;
      } else {
        (DeviceEventEmitter as unknown as { removeListener: unknown }).removeListener =
          original;
      }
    }
  });
});
