// Auto-generated by app-studio-generator.
//
// AuthApiClient (anonymous axios singleton) tests. Backs login/signup
// endpoints — must NOT register a request interceptor that would leak
// a stale Bearer token from a previous session.

jest.unmock('../../src/services/api-clients/AuthApiClient');

const mockFakeInstance: any = {
  interceptors: {
    request: { use: jest.fn() },
    response: { use: jest.fn() },
  },
};
const mockAxiosCreate = jest.fn(() => mockFakeInstance);
jest.mock('axios', () => ({
  __esModule: true,
  default: { create: (...args: any[]) => mockAxiosCreate(...args) },
  create: (...args: any[]) => mockAxiosCreate(...args),
}));

import { authApiClient } from '../../src/services/api-clients/AuthApiClient';

describe('AuthApiClient', () => {
  beforeEach(() => {
    mockAxiosCreate.mockClear();
    mockFakeInstance.interceptors.request.use.mockClear();
    mockFakeInstance.interceptors.response.use.mockClear();
    // Singleton already exists from module-load; reset its private slot
    // so configure() actually creates a new axios instance per test.
    (authApiClient as any)._axiosInstance = undefined;
  });

  it('exports a singleton', () => {
    const Ctor: any = (authApiClient as any).constructor;
    if (typeof Ctor?.getInstance === 'function') {
      expect(Ctor.getInstance()).toBe(authApiClient);
    } else {
      // Some variants export the resolved instance only. Just confirm
      // the exported value has the contract we need.
      expect(authApiClient).toBeDefined();
    }
  });

  it('getApiClient throws before configure() is called', () => {
    expect(() => authApiClient.getApiClient()).toThrow(/not configured/i);
  });

  it('configure() creates an axios instance with auth base URL + Content-Type header', () => {
    authApiClient.configure({
      authBaseUrl: 'https://auth.example.com',
      envId: 'env-test',
    });
    expect(mockAxiosCreate).toHaveBeenCalledTimes(1);
    const cfg = mockAxiosCreate.mock.calls[0][0];
    expect(cfg.baseURL).toBe('https://auth.example.com');
    expect(cfg.headers).toEqual(
      expect.objectContaining({ 'Content-Type': 'application/json' })
    );
  });

  it('configure() is idempotent — calling twice does not replace the existing client', () => {
    authApiClient.configure({ authBaseUrl: 'https://auth.example.com', envId: 'e1' });
    authApiClient.configure({ authBaseUrl: 'https://other.example.com', envId: 'e2' });
    expect(mockAxiosCreate).toHaveBeenCalledTimes(1);
  });

  it('does NOT register a request interceptor (anonymous client)', () => {
    authApiClient.configure({ authBaseUrl: 'https://auth.example.com', envId: 'e' });
    // Critical invariant: this client must never auto-attach Authorization.
    expect(mockFakeInstance.interceptors.request.use).not.toHaveBeenCalled();
  });

  it('getApiClient returns the configured axios instance', () => {
    authApiClient.configure({ authBaseUrl: 'https://auth.example.com', envId: 'e' });
    expect(authApiClient.getApiClient()).toBe(mockFakeInstance);
  });
});
