// Auto-generated by app-studio-generator.
//
// AuthorizedApiClient request-interceptor tests. Verifies every outbound
// request gets `Authorization: Bearer <token>` from secure storage and
// the `x-app-id` header. Regressions here leak unauthenticated traffic.

jest.unmock('../../src/services/api-clients/AuthorizedApiClient');

// In-memory token + appId stubs the test can flip per-case.
let mockKeychainValue: string | null | undefined = null;
let mockAppId: string | undefined = undefined;

jest.mock('@/utils/secureStorage', () => ({
  keychainData: jest.fn(async () => mockKeychainValue),
  removeKeychainData: jest.fn(async () => true),
  setKeychainData: jest.fn(async () => true),
}));

jest.mock('react-native-config', () => ({
  __esModule: true,
  default: new Proxy({}, {
    get: (_t, prop) => (prop === 'APPLICATION_ID' ? mockAppId : undefined),
  }),
}));

// Bypass real axios — we want to capture which interceptor function the
// client registers, then call it directly with a fake request object.
const mockRequestInterceptors: any[] = [];
const mockResponseInterceptorsSuccess: any[] = [];
const mockResponseInterceptorsFailed: any[] = [];
const mockFakeInstance = {
  interceptors: {
    request: { use: jest.fn(fn => mockRequestInterceptors.push(fn)) },
    response: {
      use: jest.fn((onOk, onFail) => {
        mockResponseInterceptorsSuccess.push(onOk);
        mockResponseInterceptorsFailed.push(onFail);
      }),
    },
  },
};
jest.mock('axios', () => ({
  __esModule: true,
  default: {
    create: jest.fn(() => mockFakeInstance),
  },
  create: jest.fn(() => mockFakeInstance),
}));

import { createAuthorizedApiClient } from '../../src/services/api-clients/AuthorizedApiClient';

describe('AuthorizedApiClient', () => {
  beforeEach(() => {
    mockKeychainValue = null;
    mockAppId = undefined;
    mockRequestInterceptors.length = 0;
    mockResponseInterceptorsSuccess.length = 0;
    mockResponseInterceptorsFailed.length = 0;
  });

  it('registers exactly one request interceptor and one response interceptor', () => {
    createAuthorizedApiClient('https://api.example.com');
    expect(mockRequestInterceptors).toHaveLength(1);
    expect(mockResponseInterceptorsSuccess).toHaveLength(1);
    expect(mockResponseInterceptorsFailed).toHaveLength(1);
  });

  it('attaches Bearer header when keychain returns a token', async () => {
    mockKeychainValue = 'access-token-xyz';
    createAuthorizedApiClient('https://api.example.com');
    const onRequest = mockRequestInterceptors[0];
    const req: any = { headers: {} };
    await onRequest(req);
    expect(req.headers.Authorization).toBe('Bearer access-token-xyz');
  });

  it('does NOT attach Authorization when keychain returns null', async () => {
    mockKeychainValue = null;
    createAuthorizedApiClient('https://api.example.com');
    const onRequest = mockRequestInterceptors[0];
    const req: any = { headers: {} };
    await onRequest(req);
    expect(req.headers.Authorization).toBeUndefined();
  });

  it('does NOT attach Authorization when keychain returns empty string', async () => {
    mockKeychainValue = '';
    createAuthorizedApiClient('https://api.example.com');
    const onRequest = mockRequestInterceptors[0];
    const req: any = { headers: {} };
    await onRequest(req);
    expect(req.headers.Authorization).toBeUndefined();
  });

  it('attaches x-app-id header when Config.APPLICATION_ID is set', async () => {
    mockKeychainValue = 'access-token';
    mockAppId = 'my-app-123';
    createAuthorizedApiClient('https://api.example.com');
    const onRequest = mockRequestInterceptors[0];
    const req: any = { headers: {} };
    await onRequest(req);
    expect(req.headers['x-app-id']).toBe('my-app-123');
  });

  it('does NOT attach x-app-id when Config.APPLICATION_ID is missing', async () => {
    mockKeychainValue = 'access-token';
    mockAppId = undefined;
    createAuthorizedApiClient('https://api.example.com');
    const onRequest = mockRequestInterceptors[0];
    const req: any = { headers: {} };
    await onRequest(req);
    expect(req.headers['x-app-id']).toBeUndefined();
  });

  it('response success interceptor returns the response unchanged', () => {
    createAuthorizedApiClient('https://api.example.com');
    const onOk = mockResponseInterceptorsSuccess[0];
    const fakeResp = { status: 200, data: { id: 1 } };
    expect(onOk(fakeResp)).toBe(fakeResp);
  });

  it('response failure interceptor re-rejects the error', async () => {
    createAuthorizedApiClient('https://api.example.com');
    const onFail = mockResponseInterceptorsFailed[0];
    const err = new Error('boom');
    await expect(onFail(err)).rejects.toBe(err);
  });
});
