// Auto-generated by app-studio-generator.
// Lightweight mock of app-studio-widgets so screen tests don't pull native deps.
// Each AS* component is replaced with a plain RN primitive that forwards
// testID and the common event/value props.
const React = require('react');
const RN = require('react-native');

const passthrough = (Component) =>
  React.forwardRef((props, ref) => {
    const { testId, testID, children, ...rest } = props || {};
    return React.createElement(
      Component,
      { ref, testID: testID || testId, ...rest },
      children
    );
  });

// ASForm delegates to the stateful Formik mock from jest.setup.ts — that
// mock handles state, validation, and innerRef population.
const ASFormMock = React.forwardRef((props, ref) => {
  const {
    testId,
    testID,
    children,
    innerRef,
    initialValues,
    validationSchema,
    onSubmit,
    validate,
    ...rest
  } = props || {};
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { Formik } = require('formik');
  return React.createElement(
    RN.View,
    { ref, testID: testID || testId, ...rest },
    React.createElement(
      Formik,
      {
        initialValues: initialValues || {},
        validationSchema,
        onSubmit,
        innerRef,
        validate,
      },
      children
    )
  );
});

const ASView = passthrough(RN.View);
const ASTextPrim = passthrough(RN.Text);
const ASTouchablePrim = passthrough(RN.TouchableOpacity);
const ASImagePrim = passthrough(RN.Image);
const ASScrollPrim = passthrough(RN.ScrollView);
const ASFlatListPrim = passthrough(RN.FlatList);
const ASSwitchPrim = passthrough(RN.Switch);

// List mock that executes renderItem with a recursive-Proxy fixture so
// list-item descendants are queryable from screen tests. Real FlatList
// doesn't paint in jsdom; without this, list-item widgets stay dead.
// Any property access on the fixture resolves to another Proxy so
// renderItem bodies that dereference unknown fields don't crash.
const createFixtureItem = () => {
  const handler = {
    get(_target, prop) {
      if (prop === Symbol.toPrimitive) return () => 'fixture';
      if (prop === 'toString' || prop === 'valueOf') return () => 'fixture';
      if (prop === '$$typeof' || prop === '_owner') return undefined;
      if (prop === 'length') return 0;
      if (typeof prop === 'symbol') return undefined;
      return new Proxy({}, handler);
    },
  };
  return new Proxy({}, handler);
};

const ASListMock = React.forwardRef((props, ref) => {
  const { testId, testID, data, renderItem, ListEmptyComponent, children, ...rest } =
    props || {};
  const items = Array.isArray(data) && data.length > 0 ? data : [createFixtureItem()];
  const rendered = items
    .map((item, index) => {
      if (typeof renderItem !== 'function') return null;
      try {
        const node = renderItem({ item, index, separators: {} });
        if (!node) return null;
        const itemKey = item?.id ?? item?.key ?? String(index);
        return React.cloneElement(node, { key: itemKey });
      } catch {
        return null;
      }
    })
    .filter(Boolean);
  return React.createElement(
    RN.View,
    { ref, testID: testID || testId, ...rest },
    rendered.length > 0 ? rendered : children
  );
});

// Input mock that reads Formik field state via `useField(name)` and
// renders the error message when `meta.touched && meta.error` — required
// for validation tests to find the error text via queryByText.
const ASInputPrim = React.forwardRef((props, ref) => {
  const { testId, testID, name, label, children, ...rest } = props || {};
  let formik;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    formik = require('formik');
  } catch {
    formik = null;
  }
  // useField must be called every render (rules of hooks). Our mocked
  // useField returns safe defaults when not inside a Formik provider.
  const fieldName = name || '';
  let meta = { error: undefined, touched: false };
  if (formik?.useField) {
    try {
      const result = formik.useField(fieldName);
      if (Array.isArray(result)) meta = result[1] || meta;
    } catch {
      /* useField may throw outside provider — fall back to safe meta */
    }
  }
  const showError = !!(fieldName && meta?.error && meta?.touched);
  let errorText = '';
  if (showError) {
    errorText = typeof meta.error === 'string' ? meta.error : JSON.stringify(meta.error);
  }
  return React.createElement(
    RN.View,
    null,
    React.createElement(RN.TextInput, {
      ref,
      testID: testID || testId,
      ...rest,
    }),
    showError &&
      React.createElement(
        RN.Text,
        { testID: 'error-' + (testId || fieldName) },
        errorText
      )
  );
});

// Map every known widget type to a primitive. New widgets default to View.
const widgetMap = {
  // containers
  ASContainer: ASView,
  ASColumn: ASView,
  ASRow: ASView,
  ASStack: ASView,
  ASCard: ASView,
  ASForm: ASFormMock,
  ASScrollView: ASScrollPrim,
  ASSafeArea: ASView,
  // text/display
  ASText: ASTextPrim,
  ASExpandableText: ASTextPrim,
  ASAppBar: ASView,
  ASBadge: ASTextPrim,
  ASTimer: ASTextPrim,
  ASImage: ASImagePrim,
  ASIcon: ASImagePrim,
  // buttons
  ASButton: ASTouchablePrim,
  ASIconButton: ASTouchablePrim,
  ASFloatingActionButton: ASTouchablePrim,
  ASDualIconRowButton: ASTouchablePrim,
  ASSwipeButton: ASTouchablePrim,
  // toggles
  ASCheckBox: ASSwitchPrim,
  ASSwitch: ASSwitchPrim,
  ASRadioButton: ASSwitchPrim,
  // inputs
  ASTextField: ASInputPrim,
  // Use the same Formik-aware input mock as ASTextField so error rendering
  // works for both. secureTextEntry is forced via prop default.
  ASPasswordTextField: React.forwardRef((props, ref) =>
    React.createElement(ASInputPrim, { ref, secureTextEntry: true, ...props })
  ),
  ASRichText: ASInputPrim,
  ASPin: ASInputPrim,
  // selection
  ASDropDown: ASTouchablePrim,
  ASChoiceChips: ASView,
  ASDatePicker: ASTouchablePrim,
  ASSlider: ASView,
  // list — fixture-rendering mock so item descendants are queryable.
  ASList: ASListMock,
  ASListView: ASListMock,
  ASFlatList: ASListMock,
  ASGridView: ASListMock,
  // overlays
  ASPopUp: ASView,
  ASModal: ASView,
  ASBottomSheet: ASView,
};

module.exports = new Proxy(widgetMap, {
  get(target, key) {
    if (key in target) return target[key];
    if (key === '__esModule') return true;
    if (typeof key !== 'string') return undefined;
    // Default-import support. `import ASText from '@/components/ASText'`
    // resolves to the mock module, then accesses `.default`. Without this
    // the default is undefined and React throws "type is invalid -- got
    // object". Returning ASView keeps any default-imported AS* component
    // renderable.
    if (key === 'default') return ASView;
    if (key.startsWith('AS')) return ASView;
    return undefined;
  },
});
