// Auto-generated by app-studio-generator.
// Catch-all stub for @/assets imports. Returns empty strings at deeper
// levels so component code like `color.brand.primary` or
// `theme.text.body.medium` resolves to a valid (string) value — RN
// treats `''` as "no explicit color" without throwing on style merge.
// Tests don't depend on real theme values; those come from the app at
// runtime.
function stubCallable() {
  return '';
}

function makeStub(depth) {
  return new Proxy(stubCallable, {
    get(_target, key) { // NOSONAR (S3800) — Proxy get-trap intentionally returns mixed types
      if (key === '__esModule') return true;
      if (key === Symbol.toPrimitive) {
        // Numeric hint: return 0 so callers like `String.fromCodePoint(stub)`
        // (icon resolvers reading from a glyphMap JSON we proxied) don't
        // blow up with `RangeError: Invalid code point NaN`. Default hint
        // returns an empty string — valid color value without picking one.
        return (hint) => (hint === 'number' ? 0 : '');
      }
      if (key === Symbol.iterator) {
        // Make stub iterable as an empty array so destructuring doesn't throw
        return function* () {};
      }
      if (typeof key === 'symbol') return undefined;
      // Numeric keys (e.g. space[2], radius[4]) → return a finite number
      if (typeof key === 'string' && /^\d+$/.test(key)) return 0;
      if (key === 'length') return 0;
      if (depth >= 4) return '';
      if (key === 'default') return makeStub(depth + 1);
      return makeStub(depth + 1);
    },
    apply() {
      return '';
    },
  });
}

const stub = makeStub(0);
module.exports = stub;
module.exports.default = stub;
