// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import CreateTransfer from '../../src/screens/CreateTransfer/CreateTransfer';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('CreateTransfer', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<CreateTransfer route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["CreateTransfer_Input_Background_Input","CreateTransfer_Input_SymQ20248812_Input","CreateTransfer_Input_Rec99234410_Input","CreateTransfer_Input_EgrentPayment_Input"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<CreateTransfer route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it('opens CreateTransfer_Container_Options_DropDown on press', () => {
  const screen = renderScreen(<CreateTransfer route={route} navigation={navigation} />);
  const [target] = screen.queryAllByTestId('CreateTransfer_Container_Options_DropDown');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  expect(target).toBeOnTheScreen();
  });

});
