// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import CreateQuote from '../../src/screens/CreateQuote/CreateQuote';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('CreateQuote', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<CreateQuote route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["CreateQuote_Container_BackgroundBorder_DropDown","CreateQuote_Container_BackgroundBorder_DropDown_2","CreateQuote_Container_Options_DropDown"])('opens %s on press', (testId) => {
    const screen = renderScreen(<CreateQuote route={route} navigation={navigation} />);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    expect(target).toBeOnTheScreen();
  });

});
