// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import CreateRecepient from '../../src/screens/CreateRecepient/CreateRecepient';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('CreateRecepient', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<CreateRecepient route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["CreateRecepient_Input_EnterRecipientFullName_Input","CreateRecepient_Input_Egit60X054281110100000012_Input","CreateRecepient_Input_Egit60X054281110100000012_Input_2","CreateRecepient_Input_Eg000123456789_Input","CreateRecepient_Input_Egbocelklx_Input","CreateRecepient_Input_Eg201585_Input","CreateRecepient_Input","CreateRecepient_Input_2","CreateRecepient_Input_3","CreateRecepient_Input_Gb_Input","CreateRecepient_Input_4"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<CreateRecepient route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it.each(["CreateRecepient_Container_Options_DropDown","CreateRecepient_Container_Options_DropDown_2","CreateRecepient_Container_Options_DropDown_3"])('opens %s on press', (testId) => {
    const screen = renderScreen(<CreateRecepient route={route} navigation={navigation} />);
    const [target] = screen.queryAllByTestId(testId);
    expect(target).toBeTruthy();
    fireEvent.press(target);
    expect(target).toBeOnTheScreen();
  });

});
