// Auto-generated by app-studio-generator.
import React from 'react';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import FinishScreen from '../../src/screens/FinishScreen/FinishScreen';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('FinishScreen', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<FinishScreen route={route} navigation={navigation} />)).not.toThrow();
  });

});
