// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import FundTransfer from '../../src/screens/FundTransfer/FundTransfer';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('FundTransfer', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<FundTransfer route={route} navigation={navigation} />)).not.toThrow();
  });

  it('renders list container FundTransfer_List_ContainerList_List', () => {
  const screen = renderScreen(<FundTransfer route={route} navigation={navigation} />);
  expect(screen.getByTestId('FundTransfer_List_ContainerList_List')).toBeOnTheScreen();
  });

  it('updates value on changeText for FundTransfer_Input_PartnerReferenceOptional_Input', () => {
  const screen = renderScreen(<FundTransfer route={route} navigation={navigation} />);
  const [input] = screen.queryAllByTestId('FundTransfer_Input_PartnerReferenceOptional_Input');
  expect(input).toBeTruthy();
  fireEvent.changeText(input, 'sample-value');
  });

});
