// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import Login from '../../src/screens/Login/Login';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('Login', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<Login route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["Login_Input_EgalexExampleCom_Input","Login_Input"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<Login route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it('applies secureTextEntry on Login_Input', () => {
  const screen = renderScreen(<Login route={route} navigation={navigation} />);
  const [el] = screen.queryAllByTestId('Login_Input');
  expect(el).toBeTruthy();
  expect(el.props.secureTextEntry === true || el.findByProps).toBeTruthy();
  });

});
