// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import SignUp from '../../src/screens/SignUp/SignUp';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('SignUp', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<SignUp route={route} navigation={navigation} />)).not.toThrow();
  });

  it.each(["SignUp_Input_EnterYourFullName_Input","SignUp_Input_Email_Input","SignUp_Input_CreateApassword_Input","SignUp_Input_RepeatYourPassword_Input"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

  it('applies secureTextEntry on SignUp_Input_CreateApassword_Input', () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  const [el] = screen.queryAllByTestId('SignUp_Input_CreateApassword_Input');
  expect(el).toBeTruthy();
  expect(el.props.secureTextEntry === true || el.findByProps).toBeTruthy();
  });

  it('applies secureTextEntry on SignUp_Input_RepeatYourPassword_Input', () => {
  const screen = renderScreen(<SignUp route={route} navigation={navigation} />);
  const [el] = screen.queryAllByTestId('SignUp_Input_RepeatYourPassword_Input');
  expect(el).toBeTruthy();
  expect(el.props.secureTextEntry === true || el.findByProps).toBeTruthy();
  });

});
