// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import UpdateQuote from '../../src/screens/UpdateQuote/UpdateQuote';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('UpdateQuote', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<UpdateQuote route={route} navigation={navigation} />)).not.toThrow();
  });

  it('opens UpdateQuote_Container_BackgroundBorder_DropDown on press', () => {
  const screen = renderScreen(<UpdateQuote route={route} navigation={navigation} />);
  const [target] = screen.queryAllByTestId('UpdateQuote_Container_BackgroundBorder_DropDown');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  expect(target).toBeOnTheScreen();
  });

  it.each(["UpdateQuote_Input_EnterRecipientFullName_Input","UpdateQuote_Input_EnterRecipientFullName_Input_2"])('updates value on changeText for %s', (testId) => {
    const screen = renderScreen(<UpdateQuote route={route} navigation={navigation} />);
    const [input] = screen.queryAllByTestId(testId);
    expect(input).toBeTruthy();
    fireEvent.changeText(input, 'sample-value');
  });

});
