// Auto-generated by app-studio-generator.
import React from 'react';
import { fireEvent, waitFor } from '@testing-library/react-native';
import { renderScreen } from '../render';
import { mockNavigate, mockGoBack } from '../setup';
import WelcomeScreen from '../../src/screens/WelcomeScreen/WelcomeScreen';

// react-navigation passes `route` and `navigation` as props in production.
// Provide minimal stubs so screens that destructure `route.params` survive.
const route = { params: {}, name: 'MockRoute', key: 'mock-key' };
const navigation = { navigate: mockNavigate, goBack: mockGoBack };


describe('WelcomeScreen', () => {
  it('renders without crashing', () => {
  expect(() => renderScreen(<WelcomeScreen route={route} navigation={navigation} />)).not.toThrow();
  });

  it('fires onPress on WelcomeScreen_Cta_SignUp_Button', async () => {
  const screen = renderScreen(<WelcomeScreen route={route} navigation={navigation} />);
  const [target] = screen.queryAllByTestId('WelcomeScreen_Cta_SignUp_Button');
  expect(target).toBeTruthy();
  fireEvent.press(target);
  await waitFor(() => {
  expect(mockNavigate).toHaveBeenCalledWith('SignUp', expect.anything());
  });
  });

});
