// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASAppbar from '../../src/components/ASAppbar';

describeComponentContract(
  'ASAppbar',
  (baseProps) => <ASAppbar {...baseProps}  />,
  (baseProps) => {
  }
);
