// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASAppHeader from '../../src/components/ASAppHeader';

describeComponentContract(
  'ASAppHeader',
  (baseProps) => <ASAppHeader {...baseProps} headerTitle={{ alignment: 'left' }} />,
  (baseProps) => {
  }
);
