// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASBadge from '../../src/components/ASBadge';

describeComponentContract(
  'ASBadge',
  (baseProps) => <ASBadge {...baseProps}  />,
  (baseProps) => {
  }
);
