// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASBottomSheet from '../../src/components/ASBottomSheet';

describeComponentContract(
  'ASBottomSheet',
  (baseProps) => <ASBottomSheet {...baseProps} visible={true} />,
  (baseProps) => {
  }
);
