// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASButton from '../../src/components/ASButton';

describeComponentContract(
  'ASButton',
  (baseProps) => <ASButton {...baseProps}  />,
  (baseProps) => {
  it('fires onPress when enabled', () => {
    const handler = jest.fn();
    const { getAllByTestId } = render(
      <ASButton {...baseProps}  onPress={handler} />
    );
    const [target] = getAllByTestId(/ASButton-test/);
    fireEvent.press(target);
    expect(handler).toHaveBeenCalled();
  });

  it('propagates disabled prop to the underlying touchable', () => {
    // RN's TouchableOpacity forwards `disabled` to a Pressable, which
    // on the host node surfaces as either `props.disabled` directly
    // or `props.accessibilityState.disabled` (depending on RN version).
    // Accept either path to keep the test robust across versions.
    const { getAllByTestId } = render(
      <ASButton {...baseProps}  disabled={true} />
    );
    const targets = getAllByTestId(/ASButton-test/);
    const found = targets.some(t =>
      t.props.disabled === true ||
      t.props.accessibilityState?.disabled === true
    );
    expect(found).toBe(true);
  });

  it('renders with loading={true}', () => {
    expect(() =>
      render(<ASButton {...baseProps}  loading={true} />)
    ).not.toThrow();
  });

  it('renders with simpleTextButton={true}', () => {
    expect(() =>
      render(<ASButton {...baseProps}  simpleTextButton={true} />)
    ).not.toThrow();
  });

  it('renders with iconPosition={"trailing"}', () => {
    expect(() =>
      render(<ASButton {...baseProps}  iconPosition="trailing" />)
    ).not.toThrow();
  });

  it('renders with minHeight + maxHeight clamp', () => {
    expect(() =>
      render(<ASButton {...baseProps}  minHeight={40} maxHeight={120} />)
    ).not.toThrow();
  });

  }
);
