// Auto-generated by app-studio-generator.
import React from 'react';
import { render } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASChoicechips from '../../src/components/ASChoicechips';

describeComponentContract(
  'ASChoicechips',
  (baseProps) => <ASChoicechips {...baseProps} options={[]} />,
  (baseProps) => {
  it('renders provided options', () => {
    const opts = [
      { id: 'a', label: 'Option A' },
      { id: 'b', label: 'Option B' },
    ];
    const { queryByText } = render(
      <ASChoicechips {...baseProps} options={opts} />
    );
    // Either label or full chip should be rendered. The lib varies
    // its label rendering, so we just check at least one exists.
    const found = queryByText('Option A') || queryByText('Option B');
    expect(found).toBeTruthy();
  });

  }
);
