// Auto-generated by app-studio-generator.
import React from 'react';
import { render } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASCheckBox from '../../src/components/ASCheckBox';

describeComponentContract(
  'ASCheckBox',
  (baseProps) => <ASCheckBox {...baseProps}  />,
  (baseProps) => {
  it('renders with value={true} (checked state)', () => {
    expect(() =>
      render(<ASCheckBox {...baseProps}  value={true} />)
    ).not.toThrow();
  });

  it('renders with disabled={true} (greyed variant)', () => {
    expect(() =>
      render(<ASCheckBox {...baseProps}  disabled={true} />)
    ).not.toThrow();
  });

  it('renders with populated options array', () => {
    const fixture = [
      { label: 'Option A', value: 'a' },
      { label: 'Option B', value: 'b' },
    ];
    expect(() =>
      render(
        <ASCheckBox
          {...baseProps}
          options={fixture}
          data={fixture}
          items={fixture}
        />
      )
    ).not.toThrow();
  });

  }
);
