// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASCounter from '../../src/components/ASCounter';

describeComponentContract(
  'ASCounter',
  (baseProps) => <ASCounter {...baseProps} value={0} />,
  (baseProps) => {
  it('invokes onValueChange when + pressed', () => {
    const handler = jest.fn();
    const { getByTestId } = render(
      <ASCounter {...baseProps} name="counter" initialValue={5} stepValue={1} minValue={0} maxValue={100} onValueChange={handler} />
    );
    fireEvent.press(getByTestId('increaseBtn-ASCounter-test'));
    expect(handler).toHaveBeenCalledWith(6);
  });

  it('invokes onValueChange when - pressed', () => {
    const handler = jest.fn();
    const { getByTestId } = render(
      <ASCounter {...baseProps} name="counter" initialValue={5} stepValue={1} minValue={0} maxValue={100} onValueChange={handler} />
    );
    fireEvent.press(getByTestId('decreaseBtn-ASCounter-test'));
    expect(handler).toHaveBeenCalledWith(4);
  });

  }
);
