// Auto-generated by app-studio-generator.
import React from 'react';
import { testDefaults } from '../setup';
import { describeComponentContract } from '../helpers/component-contract';
import ASDatePicker from '../../src/components/ASDatePicker';

describeComponentContract(
  'ASDatePicker',
  (baseProps) => <ASDatePicker {...baseProps} value={testDefaults.today()} />,
  (baseProps) => {
  }
);
