// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASDivider from '../../src/components/ASDivider';

describeComponentContract(
  'ASDivider',
  (baseProps) => <ASDivider {...baseProps}  />,
  (baseProps) => {
  }
);
