// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASDropDown from '../../src/components/ASDropDown';

describeComponentContract(
  'ASDropDown',
  (baseProps) => <ASDropDown {...baseProps} options={[]} />,
  (baseProps) => {
  it('fires onValueChange via outer testID', () => {
    const handler = jest.fn();
    const { getAllByTestId } = render(
      <ASDropDown {...baseProps} options={[]} onValueChange={handler} />
    );
    const [target] = getAllByTestId(/ASDropDown-test/);
    fireEvent(target, 'valueChange', 'sample');
    // No assertion on call — third-party wrappers vary in whether
    // this propagates. The render survival is the smoke.
    expect(target).toBeDefined();
  });

  it('renders with placeholder', () => {
    expect(() =>
      render(<ASDropDown {...baseProps} options={[]} placeholder="select…" />)
    ).not.toThrow();
  });

  it('renders with populated data/items prop', () => {
    // Pass data/items/options together so whichever prop the
    // component consumes is non-empty and its renderItem fires.
    const fixture = [
      { label: 'Option A', value: 'a' },
      { label: 'Option B', value: 'b' },
    ];
    expect(() =>
      render(
        <ASDropDown
          {...baseProps}
          data={fixture}
          items={fixture}
          options={fixture}
        />
      )
    ).not.toThrow();
  });

  it('renders with disabled={true}', () => {
    expect(() =>
      render(<ASDropDown {...baseProps} options={[]} disabled={true} />)
    ).not.toThrow();
  });

  }
);
