// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASExpandableText from '../../src/components/ASExpandableText';

describeComponentContract(
  'ASExpandableText',
  (baseProps) => <ASExpandableText {...baseProps}  />,
  (baseProps) => {
  }
);
