// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASFloatingActionButton from '../../src/components/ASFloatingActionButton';

describeComponentContract(
  'ASFloatingActionButton',
  (baseProps) => <ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' />,
  (baseProps) => {
  it('fires onPress when enabled', () => {
    const handler = jest.fn();
    const { getAllByTestId } = render(
      <ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' onPress={handler} />
    );
    const [target] = getAllByTestId(/ASFloatingActionButton-test/);
    fireEvent.press(target);
    expect(handler).toHaveBeenCalled();
  });

  it('propagates disabled prop to the underlying touchable', () => {
    // RN's TouchableOpacity forwards `disabled` to a Pressable, which
    // on the host node surfaces as either `props.disabled` directly
    // or `props.accessibilityState.disabled` (depending on RN version).
    // Accept either path to keep the test robust across versions.
    const { getAllByTestId } = render(
      <ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' disabled={true} />
    );
    const targets = getAllByTestId(/ASFloatingActionButton-test/);
    const found = targets.some(t =>
      t.props.disabled === true ||
      t.props.accessibilityState?.disabled === true
    );
    expect(found).toBe(true);
  });

  it('renders with loading={true}', () => {
    expect(() =>
      render(<ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' loading={true} />)
    ).not.toThrow();
  });

  it('renders with simpleTextButton={true}', () => {
    expect(() =>
      render(<ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' simpleTextButton={true} />)
    ).not.toThrow();
  });

  it('renders with iconPosition={"trailing"}', () => {
    expect(() =>
      render(<ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' iconPosition="trailing" />)
    ).not.toThrow();
  });

  it('renders with minHeight + maxHeight clamp', () => {
    expect(() =>
      render(<ASFloatingActionButton {...baseProps} floatingPosition='bottom-right' minHeight={40} maxHeight={120} />)
    ).not.toThrow();
  });

  }
);
