// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASForm from '../../src/components/ASForm';

describeComponentContract(
  'ASForm',
  (baseProps) => <ASForm {...baseProps}  />,
  (baseProps) => {
  }
);
