// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASIconButton from '../../src/components/ASIconButton';

describeComponentContract(
  'ASIconButton',
  (baseProps) => <ASIconButton {...baseProps}  />,
  (baseProps) => {
  it('fires onPress when enabled', () => {
    const handler = jest.fn();
    const { getAllByTestId } = render(
      <ASIconButton {...baseProps}  onPress={handler} />
    );
    const [target] = getAllByTestId(/ASIconButton-test/);
    fireEvent.press(target);
    expect(handler).toHaveBeenCalled();
  });

  it('renders with loading={true}', () => {
    expect(() =>
      render(<ASIconButton {...baseProps}  loading={true} />)
    ).not.toThrow();
  });

  it('renders with simpleTextButton={true}', () => {
    expect(() =>
      render(<ASIconButton {...baseProps}  simpleTextButton={true} />)
    ).not.toThrow();
  });

  it('renders with iconPosition={"trailing"}', () => {
    expect(() =>
      render(<ASIconButton {...baseProps}  iconPosition="trailing" />)
    ).not.toThrow();
  });

  it('renders with minHeight + maxHeight clamp', () => {
    expect(() =>
      render(<ASIconButton {...baseProps}  minHeight={40} maxHeight={120} />)
    ).not.toThrow();
  });

  }
);
