// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASImage from '../../src/components/ASImage';

describeComponentContract(
  'ASImage',
  (baseProps) => <ASImage {...baseProps}  />,
  (baseProps) => {
  }
);
