// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASListTile from '../../src/components/ASListTile';

describeComponentContract(
  'ASListTile',
  (baseProps) => <ASListTile {...baseProps} title='item' />,
  (baseProps) => {
  }
);
