// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASListView from '../../src/components/ASListView';

describeComponentContract(
  'ASListView',
  (baseProps) => <ASListView {...baseProps} data={[]} />,
  (baseProps) => {
  }
);
