// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASLoadingIndicator from '../../src/components/ASLoadingIndicator';

describeComponentContract(
  'ASLoadingIndicator',
  (baseProps) => <ASLoadingIndicator {...baseProps} loading={true} visible={true} />,
  (baseProps) => {
  }
);
