// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASLoadingScreen from '../../src/components/ASLoadingScreen';

describeComponentContract(
  'ASLoadingScreen',
  (baseProps) => <ASLoadingScreen {...baseProps} loading={true} visible={true} />,
  (baseProps) => {
  }
);
