// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASModal from '../../src/components/ASModal';

describeComponentContract(
  'ASModal',
  (baseProps) => <ASModal {...baseProps} visible={true} />,
  (baseProps) => {
  }
);
