// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASOverlay from '../../src/components/ASOverlay';

describeComponentContract(
  'ASOverlay',
  (baseProps) => <ASOverlay {...baseProps}  />,
  (baseProps) => {
  }
);
