// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASPageView from '../../src/components/ASPageView';

describeComponentContract(
  'ASPageView',
  (baseProps) => <ASPageView {...baseProps} pages={[]} />,
  (baseProps) => {
  }
);
