// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASPageViewPage from '../../src/components/ASPageViewPage';

describeComponentContract(
  'ASPageViewPage',
  (baseProps) => <ASPageViewPage {...baseProps}  />,
  (baseProps) => {
  }
);
