// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASPin from '../../src/components/ASPin';

describeComponentContract(
  'ASPin',
  (baseProps) => <ASPin {...baseProps} length={4} />,
  (baseProps) => {
  }
);
