// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASPopUp from '../../src/components/ASPopUp';

describeComponentContract(
  'ASPopUp',
  (baseProps) => <ASPopUp {...baseProps}  />,
  (baseProps) => {
  }
);
