// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASProgressBar from '../../src/components/ASProgressBar';

describeComponentContract(
  'ASProgressBar',
  (baseProps) => <ASProgressBar {...baseProps} progress={0} />,
  (baseProps) => {
  }
);
