// Auto-generated by app-studio-generator.
import React from 'react';
import { render } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASRichText from '../../src/components/ASRichText';

describeComponentContract(
  'ASRichText',
  (baseProps) => <ASRichText {...baseProps}  />,
  (baseProps) => {
  it('renders editable={false} variant', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  editable={false} />)
    ).not.toThrow();
  });

  it('renders with multiline={true}', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  multiline={true} />)
    ).not.toThrow();
  });

  it('renders with placeholder', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  placeholder="enter value" />)
    ).not.toThrow();
  });

  it('renders with autoFocus={true}', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  autoFocus={true} />)
    ).not.toThrow();
  });

  it('renders with customFlex layout', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  customFlex={1} />)
    ).not.toThrow();
  });

  it('renders with customWidth layout', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  customWidth={200} />)
    ).not.toThrow();
  });

  it('renders with customAlignSelf layout', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  customAlignSelf="center" />)
    ).not.toThrow();
  });

  it('renders with customMinWidth layout', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  customMinWidth={80} />)
    ).not.toThrow();
  });

  it('renders with defaultValue when field is empty', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  defaultValue="seed" />)
    ).not.toThrow();
  });

  it('renders with maxLength constraint', () => {
    expect(() =>
      render(<ASRichText {...baseProps}  maxLength={50} />)
    ).not.toThrow();
  });

  }
);
