// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASSlider from '../../src/components/ASSlider';

describeComponentContract(
  'ASSlider',
  (baseProps) => <ASSlider {...baseProps} minimumValue={0} maximumValue={100} value={50} />,
  (baseProps) => {
  }
);
