// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASSpacer from '../../src/components/ASSpacer';

describeComponentContract(
  'ASSpacer',
  (baseProps) => <ASSpacer {...baseProps}  />,
  (baseProps) => {
  }
);
