// Auto-generated by app-studio-generator.
import React from 'react';
import { render } from '@testing-library/react-native';
import { View } from 'react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASStack from '../../src/components/ASStack';

describeComponentContract(
  'ASStack',
  (baseProps) => <ASStack {...baseProps}  />,
  (baseProps) => {
  it('renders with child elements', () => {
    expect(() =>
      render(
        <ASStack {...baseProps} >
          <View testID="layout-child-a" style={{ flex: 1 }} />
          <View testID="layout-child-b" />
        </ASStack>
      )
    ).not.toThrow();
  });

  it('renders with scrollable={true}', () => {
    // Both `scrollable` and `isScrollable` are passed because different
    // components use different prop names (ASColumn/ASRow → scrollable,
    // ASContainer → isScrollable). RN ignores unknown props on Views.
    expect(() =>
      render(
        <ASStack {...baseProps}  scrollable={true} isScrollable={true}>
          <View />
        </ASStack>
      )
    ).not.toThrow();
  });

  it('renders with spacing between children', () => {
    expect(() =>
      render(
        <ASStack {...baseProps}  spacing={8}>
          <View />
          <View />
        </ASStack>
      )
    ).not.toThrow();
  });

  it('renders with backgroundImage prop', () => {
    expect(() =>
      render(
        <ASStack
          {...baseProps}
          
          backgroundImage="https://example.com/bg.png"
        >
          <View />
        </ASStack>
      )
    ).not.toThrow();
  });

  it('renders with style override (spacing + flex)', () => {
    // Spacial overrides only — exercises the flatten/merge path without
    // picking a color (those come from the app theme at runtime).
    expect(() =>
      render(
        <ASStack
          {...baseProps}
          
          style={{ padding: 16, margin: 8, flex: 1 }}
        >
          <View />
        </ASStack>
      )
    ).not.toThrow();
  });

  it('renders with gradient style', () => {
    // Exercises the gradient* flatten path. Color values are empty
    // strings (valid color shape, no theme association) — the test
    // only checks that the keys traverse the flatten without throwing.
    expect(() =>
      render(
        <ASStack
          {...baseProps}
          
          style={{
            // @ts-ignore — gradient* keys are component-internal, not RN ViewStyle
            gradientType: 'linear',
            gradientColors: ['', ''],
            gradientStart: { x: 0, y: 0 },
            gradientEnd: { x: 1, y: 1 },
          }}
        >
          <View />
        </ASStack>
      )
    ).not.toThrow();
  });

  }
);
