// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASSwipeButton from '../../src/components/ASSwipeButton';

describeComponentContract(
  'ASSwipeButton',
  (baseProps) => <ASSwipeButton {...baseProps}  />,
  (baseProps) => {
  }
);
