// Auto-generated by app-studio-generator.
import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASSwitch from '../../src/components/ASSwitch';

describeComponentContract(
  'ASSwitch',
  (baseProps) => <ASSwitch {...baseProps}  />,
  (baseProps) => {
  it('fires onValueChange', () => {
    const handler = jest.fn();
    const { getAllByTestId } = render(
      <ASSwitch {...baseProps}  onValueChange={handler} />
    );
    const [target] = getAllByTestId(/ASSwitch-test/);
    fireEvent(target, 'valueChange', true);
    expect(handler).toHaveBeenCalled();
  });

  it('renders with value={true} (checked state)', () => {
    expect(() =>
      render(<ASSwitch {...baseProps}  value={true} />)
    ).not.toThrow();
  });

  it('renders with disabled={true} (greyed variant)', () => {
    expect(() =>
      render(<ASSwitch {...baseProps}  disabled={true} />)
    ).not.toThrow();
  });

  it('renders with populated options array', () => {
    const fixture = [
      { label: 'Option A', value: 'a' },
      { label: 'Option B', value: 'b' },
    ];
    expect(() =>
      render(
        <ASSwitch
          {...baseProps}
          options={fixture}
          data={fixture}
          items={fixture}
        />
      )
    ).not.toThrow();
  });

  }
);
