// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASTab from '../../src/components/ASTab';

describeComponentContract(
  'ASTab',
  (baseProps) => <ASTab {...baseProps} tabs={[]} />,
  (baseProps) => {
  }
);
