// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASTabView from '../../src/components/ASTabView';

describeComponentContract(
  'ASTabView',
  (baseProps) => <ASTabView {...baseProps} tabs={[]} />,
  (baseProps) => {
  }
);
