// Auto-generated by app-studio-generator.
import React from 'react';
import { render } from '@testing-library/react-native';
import { describeComponentContract } from '../helpers/component-contract';
import ASText from '../../src/components/ASText';

describeComponentContract(
  'ASText',
  (baseProps) => <ASText {...baseProps}  />,
  (baseProps) => {
  it('renders labelType="number" formatted output', () => {
    const { queryByText } = render(
      <ASText {...baseProps} label={undefined} labelType="number">{12345}</ASText>
    );
    // Substring match — formatter must include this canonical fragment
    // anywhere in the rendered Text (datetime → "...2025...", etc.).
    expect(queryByText(/12,345/)).toBeTruthy();
  });

  it('renders labelType="datetime" formatted output', () => {
    const { queryByText } = render(
      <ASText {...baseProps} label={undefined} labelType="datetime">{1735689600000}</ASText>
    );
    // Substring match — formatter must include this canonical fragment
    // anywhere in the rendered Text (datetime → "...2025...", etc.).
    expect(queryByText(/2025/)).toBeTruthy();
  });

  it('renders labelType="expiry-date" formatted output', () => {
    const { queryByText } = render(
      <ASText {...baseProps} label={undefined} labelType="expiry-date">{'202512'}</ASText>
    );
    // Substring match — formatter must include this canonical fragment
    // anywhere in the rendered Text (datetime → "...2025...", etc.).
    expect(queryByText(/12\/2025/)).toBeTruthy();
  });

  it('renders labelType="card-number" formatted output', () => {
    const { queryByText } = render(
      <ASText {...baseProps} label={undefined} labelType="card-number">{'1234567812345678'}</ASText>
    );
    // Substring match — formatter must include this canonical fragment
    // anywhere in the rendered Text (datetime → "...2025...", etc.).
    expect(queryByText(/1234 5678 1234 5678/)).toBeTruthy();
  });

  it('renders default branch (no labelType) with the label as text', () => {
    const { queryByText } = render(
      <ASText {...baseProps} label='plain-label' />
    );
    expect(queryByText('plain-label')).toBeTruthy();
  });

  }
);
