// Auto-generated by app-studio-generator.
import React from 'react';
import { describeComponentContract } from '../helpers/component-contract';
import ASVerticalDivider from '../../src/components/ASVerticalDivider';

describeComponentContract(
  'ASVerticalDivider',
  (baseProps) => <ASVerticalDivider {...baseProps}  />,
  (baseProps) => {
  }
);
