// Auto-generated by app-studio-generator.
//
// Placeholder replacing the default `<App />` smoke test that ships
// with the React Native template. That default test renders the full
// app tree (all providers + native modules) which doesn't fit the
// per-screen / per-component unit-test isolation model used here.
//
// Real coverage lives under:
//   - __tests__/screens/*
//   - __tests__/components/*
//   - __tests__/services/*
//   - __tests__/context/*
describe('App', () => {
  it.skip('placeholder — see __tests__/screens/* and __tests__/components/*', () => {});
});
