// Auto-generated by app-studio-generator.
import React from 'react';
import { render, RenderOptions } from '@testing-library/react-native';

// useNavigation / useRoute / useIsFocused are mocked globally in setup.ts,
// so we don't need to wrap with NavigationContainer here.
type Wrapper = React.ComponentType<{ children: React.ReactNode }>;

const DefaultWrapper: Wrapper = ({ children }) => <>{children}</>;

export function renderScreen(
  ui: React.ReactElement,
  options?: Omit<RenderOptions, 'wrapper'> & { wrapper?: Wrapper }
) {
  const Wrapper = options?.wrapper ?? DefaultWrapper;
  return render(ui, { ...options, wrapper: Wrapper });
}
