// Auto-generated by app-studio-generator.
import '@testing-library/jest-native/extend-expect';

// --- Workflow mock bag --------------------------------------------------------
// Re-export the shared workflow-context singleton so screen tests can assert
// on any workflow trigger function by name:
//
//   import { workflowMocks } from '../setup';
//   expect(workflowMocks.fetchUserProfile1029).toHaveBeenCalled();
//
// The singleton lives in __tests__/__mocks__/workflow-context.js and is
// reached via the moduleNameMapper rule for `@/context` — but importing
// directly via a relative path is more robust to mapper changes.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const workflowContextModule = require('./__mocks__/workflow-context');
export const workflowMocks: any = workflowContextModule.__workflowMocks;

beforeEach(() => {
  // Clear all workflow trigger mocks between tests so call counts don't
  // bleed across `it(...)` blocks. Workflow triggers are Proxy-synthesized
  // (e.g. `workflowMocks.registerUser1029`) and have no own-key entry —
  // `Object.keys()` would miss them, so we use the helper that iterates
  // the internal cache.
  if (typeof workflowContextModule.__clearAllWorkflowMocks === 'function') {
    workflowContextModule.__clearAllWorkflowMocks();
  } else {
    Object.keys(workflowMocks).forEach(key => {
      const fn = workflowMocks[key];
      if (fn && typeof fn === 'function' && typeof fn.mockClear === 'function') {
        fn.mockClear();
      }
    });
  }
});

// --- Shared test defaults -----------------------------------------------------
// Runtime-evaluated sample values for component prop overrides. Using
// expressions instead of hardcoded literals keeps the generated tests
// deterministic per-run while exercising real-world variation (e.g. a
// calendar opened today crosses different month/year boundaries than
// one opened on a fixed date).
export const testDefaults = {
  today: (): string => new Date().toISOString().slice(0, 10),
  daysFromNow: (days: number): string =>
    new Date(Date.now() + days * 86400000).toISOString().slice(0, 10),
  // Render-survival placeholder for components that read style/textStyle
  // via `StyleSheet.flatten(...)` (e.g. ASButton's
  // `flattenedTextStyle.color`). An empty object survives the flatten
  // and produces `undefined` for any `.color` / `.backgroundColor` read,
  // which RN renders as "no explicit color" — actual colors come from
  // the app theme at runtime, not from this stub.
  stubStyle: (): Record<string, unknown> => ({}),
};

// --- React Navigation ---------------------------------------------------------
export const mockNavigate = jest.fn();
export const mockGoBack = jest.fn();
export const mockReplace = jest.fn();
export const mockReset = jest.fn();

const buildNav = () => ({
  navigate: mockNavigate,
  goBack: mockGoBack,
  replace: mockReplace,
  reset: mockReset,
  push: jest.fn(),
  pop: jest.fn(),
  popToTop: jest.fn(),
  dispatch: jest.fn(),
  setParams: jest.fn(),
  setOptions: jest.fn(),
  addListener: jest.fn(() => jest.fn()),
  removeListener: jest.fn(),
  isFocused: () => true,
  canGoBack: () => true,
  getId: () => 'mock-id',
  getState: () => ({ routes: [], index: 0 }),
  getParent: () => buildNav(),
});

jest.mock('@react-navigation/native', () => {
  const actual = jest.requireActual('@react-navigation/native');
  return {
    ...actual,
    useNavigation: () => buildNav(),
    useRoute: () => ({ params: {}, name: 'MockRoute', key: 'mock-key' }),
    useIsFocused: () => true,
    useFocusEffect: (cb) => cb(),
  };
});

// --- react-native-gesture-handler ---------------------------------------------
// Provides minimal stubs for the bits the generated layouts pull in.
jest.mock('react-native-gesture-handler', () => {
  const React = require('react');
  const RN = require('react-native');
  const passthrough = (Comp) => (props) =>
    React.createElement(Comp || RN.View, props, props?.children);
  return new Proxy(
    {
      GestureHandlerRootView: passthrough(RN.View),
      ScrollView: passthrough(RN.ScrollView),
      State: {},
      Directions: {},
      gestureHandlerRootHOC: (c) => c,
    },
    {
      get(target, key) {
        if (key in target) return target[key];
        return passthrough(RN.View);
      },
    }
  );
});

// app-studio-widgets is mapped to ./__mocks__/as-widgets via moduleNameMapper
// in jest.config.js — no manual jest.mock() needed here.

// Re-throw console.error during tests to surface React 19 AggregateError causes
// (React 19 swallows the underlying error otherwise).
const originalConsoleError = console.error;
console.error = (...args) => {
  originalConsoleError(...args);
  // Re-throw only for actual Errors to avoid noise from React warnings
  const first = args[0];
  if (first instanceof Error) throw first;
};

// --- Linking ------------------------------------------------------------------
jest.mock('react-native/Libraries/Linking/Linking', () => ({
  openURL: jest.fn(() => Promise.resolve()),
  canOpenURL: jest.fn(() => Promise.resolve(true)),
  addEventListener: jest.fn(() => ({ remove: jest.fn() })),
  removeEventListener: jest.fn(),
  getInitialURL: jest.fn(() => Promise.resolve(null)),
}));

// --- Formik (stateful mock with real Yup validation) -------------------------
// `<Formik>` holds its own React state and exposes it via Context so
// `useFormikContext` / `useField` see live values. Yup is NOT mocked —
// `schema.validateSync()` runs for real.
jest.mock('formik', () => {
  const React = require('react');
  const FormikContext = React.createContext(null);
  // Registry of active Formik bags — validation tests use this to call
  // `submitForm()` directly, bypassing the screen's submit-button gate.
  const formikBagRegistry: any[] = [];

  // Helper: turn a Yup ValidationError into a flat { fieldName: message } map.
  // When abortEarly:false collects multiple errors per path (e.g. required
  // AND min on an empty string), keep the FIRST one — that matches Yup's
  // chain order (required before min/max/matches) and aligns with how real
  // Formik renders errors[field] (single string per field).
  const collectYupErrors = (err) => {
    const out = {};
    if (!err) return out;
    if (Array.isArray(err.inner) && err.inner.length > 0) {
      for (const e of err.inner) {
        if (e?.path && !(e.path in out)) out[e.path] = e.message;
      }
    } else if (err.path) {
      out[err.path] = err.message;
    }
    return out;
  };

  // Workflow context returns Proxy objects for `data.xxx` accessors so
  // chained reads (`memberDetail?.roles?.[0]?.entityId`) don't crash. Those
  // proxies cause Yup to throw "item.getValue is not a function" because Yup
  // probes for Schema-like methods. Coerce non-primitive form values to
  // their Symbol.toPrimitive string ('' for our Proxy) before validation.
  const sanitizeForYup = (vals) => {
    if (!vals || typeof vals !== 'object') return vals;
    const out = {};
    for (const k of Object.keys(vals)) {
      const v = vals[k];
      if (v === null || v === undefined) { out[k] = v; continue; }
      const t = typeof v;
      if (t === 'string' || t === 'number' || t === 'boolean') { out[k] = v; continue; }
      try { out[k] = String(v); } catch { out[k] = ''; }
    }
    return out;
  };

  // Field-handler factories — hoisted above Formik so the curried inner
  // arrows live at depth ≤4 from this jest.mock callback (SonarQube S2004).
  // Each takes the live setters captured per Formik instance and returns
  // the bag-shaped helper Formik consumers expect.
  const buildHandleChange = (setFieldValue) => (f) => (v) => setFieldValue(f, v);
  const buildHandleBlur = (setFieldTouched) => (f) => () => setFieldTouched(f, true);
  const buildValidateField = (runValidation, setErrors) => (f) => {
    const errs = runValidation();
    const apply = (prev) => ({ ...prev, [f]: errs[f] });
    setErrors(apply);
  };
  const buildGetFieldProps = (values, setFieldValue, setFieldTouched) => (f) => ({
    value: values[f] ?? '',
    onChange: (v) => setFieldValue(f, v),
    onBlur: () => setFieldTouched(f, true),
    name: f,
  });
  const buildGetFieldMeta = (values, errors, touched, initial) => (f) => ({
    value: values[f],
    error: errors[f],
    touched: !!touched[f],
    initialValue: initial[f],
  });
  const buildGetFieldHelpers = (setFieldValue, setFieldTouched, setFieldError) => (f) => ({
    setValue: (v) => setFieldValue(f, v),
    setTouched: (t) => setFieldTouched(f, t),
    setError: (m) => setFieldError(f, m),
  });

  const Formik = ({
    initialValues,
    validationSchema,
    onSubmit,
    innerRef,
    children,
    // Some screens pass `validate` callback instead of (or alongside) schema
    validate,
  }) => {
    const initial = initialValues || {};
    const [values, setValuesState] = React.useState(initial);
    const [errors, setErrors] = React.useState({});
    const [touched, setTouched] = React.useState({});
    const [isSubmitting, setIsSubmitting] = React.useState(false);

    // Latest-values ref — keeps submitForm() readable across renders so
    // tests that do `setFieldValue + submitForm` on a captured bag don't
    // hit stale-closure bugs (the captured bag's `values` would otherwise
    // be the pre-update snapshot).
    const valuesRef = React.useRef(values);
    React.useEffect(() => { valuesRef.current = values; }, [values]);
    const setValues = React.useCallback((next) => {
      if (typeof next === 'function') {
        const computed = next(valuesRef.current);
        valuesRef.current = computed;
        setValuesState(computed);
      } else {
        valuesRef.current = next;
        setValuesState(next);
      }
    }, []);

    // Memoize initial JSON so `dirty` computation is stable. We capture
    // it once at mount (using ref) so subsequent renders with new
    // initialValues references don't make `dirty` flicker — real Formik
    // tracks dirty against the *first* initialValues unless
    // enableReinitialize is on (and even then only resets to the new
    // baseline, never compares against new identity).
    const initialJSONRef = React.useRef<string>('');
    if (initialJSONRef.current === '') {
      try { initialJSONRef.current = JSON.stringify(initial); } catch { initialJSONRef.current = '{}'; }
    }
    const initialJSON = initialJSONRef.current;

    const runValidation = React.useCallback(() => {
      const liveValues = valuesRef.current;
      const safeValues = sanitizeForYup(liveValues);
      let errs = {};
      if (validationSchema && typeof validationSchema.validateSync === 'function') {
        try {
          validationSchema.validateSync(safeValues, { abortEarly: false });
        } catch (err) {
          errs = collectYupErrors(err);
        }
      }
      if (typeof validate === 'function') {
        try {
          const r = validate(safeValues);
          if (r && typeof r === 'object') Object.assign(errs, r);
        } catch {
          /* user-supplied validate threw — ignore in tests */
        }
      }
      return errs;
    }, [validationSchema, validate]);

    const submitForm = React.useCallback(async () => {
      const newErrors = runValidation();
      setErrors(newErrors);
      // Mark every known field touched so error displays gated on
      // `touched[field]` show up.
      const liveValues = valuesRef.current;
      const touchedAll = {};
      Object.keys({ ...initial, ...liveValues }).forEach(k => { touchedAll[k] = true; });
      setTouched(touchedAll);
      if (Object.keys(newErrors).length === 0 && typeof onSubmit === 'function') {
        setIsSubmitting(true);
        try {
          await onSubmit(liveValues, {
            setSubmitting: setIsSubmitting,
            resetForm: () => { setValues(initial); setErrors({}); setTouched({}); },
          });
        } finally {
          setIsSubmitting(false);
        }
      }
    }, [runValidation, initial, onSubmit, setValues]);

    const setFieldValue = React.useCallback((f, v) => {
      setValues(prev => ({ ...prev, [f]: v }));
    }, []);
    const setFieldError = React.useCallback((f, m) => {
      setErrors(prev => ({ ...prev, [f]: m }));
    }, []);
    const setFieldTouched = React.useCallback((f, t = true) => {
      setTouched(prev => ({ ...prev, [f]: t }));
    }, []);

    // Auto-validate on values change so isValid/dirty reflect reality.
    // Serialized-error diff guards against re-render loops.
    React.useEffect(() => {
      const next = runValidation();
      setErrors(prev => {
        try {
          if (JSON.stringify(prev) === JSON.stringify(next)) return prev;
        } catch { /* fall through and replace */ }
        return next;
      });
    }, [values, runValidation]);

    // Real dirty: form has been mutated from its initial baseline.
    // Real isValid: no fields currently have a validation error.
    const valuesJSON = React.useMemo(() => {
      try { return JSON.stringify(values); } catch { return ''; }
    }, [values]);
    const dirty = valuesJSON !== initialJSON;
    const isValid = Object.keys(errors).length === 0;

    const bag = React.useMemo(() => {
      // Workflow tests pre-fill via `await bag.setValues({...})` (emitter
      // does this for buttons inside ASForm). Validation tests bypass
      // the submit-button gate by calling `bag.submitForm()` directly.
      return {
        values,
        errors,
        touched,
        isValid,
        dirty,
        isSubmitting,
        initialValues: initial,
        setFieldValue,
        setFieldError,
        setFieldTouched,
        setValues,
        setErrors,
        setTouched,
        handleChange: buildHandleChange(setFieldValue),
        handleBlur: buildHandleBlur(setFieldTouched),
        handleSubmit: submitForm,
        submitForm,
        resetForm: () => { setValues(initial); setErrors({}); setTouched({}); },
        validateField: buildValidateField(runValidation, setErrors),
        validateForm: async () => {
          const errs = runValidation();
          setErrors(errs);
          return errs;
        },
        getFieldProps: buildGetFieldProps(values, setFieldValue, setFieldTouched),
        getFieldMeta: buildGetFieldMeta(values, errors, touched, initial),
        getFieldHelpers: buildGetFieldHelpers(setFieldValue, setFieldTouched, setFieldError),
      };
    }, [values, errors, touched, isValid, dirty, isSubmitting, initial, initialJSON, setFieldValue, setFieldError, setFieldTouched, submitForm, runValidation]);

    // Populate innerRef synchronously so screens that read
    // `formikRef.current.setFieldValue(...)` in a press handler don't crash.
    if (innerRef && typeof innerRef === 'object' && 'current' in innerRef) {
      innerRef.current = bag;
    } else if (typeof innerRef === 'function') {
      innerRef(bag);
    }
    // Register the bag globally so validation tests can call
    // `submitForm()` directly, bypassing the screen's submit-button gate.
    formikBagRegistry.push(bag);

    return React.createElement(
      FormikContext.Provider,
      { value: bag },
      typeof children === 'function' ? children(bag) : children
    );
  };

  const useFormikContext = () => React.useContext(FormikContext) || {
    values: {}, errors: {}, touched: {},
    isValid: true, dirty: true, isSubmitting: false,
    setFieldValue: () => {}, setFieldError: () => {}, setFieldTouched: () => {},
    setValues: () => {}, setErrors: () => {}, setTouched: () => {},
    handleChange: () => () => {}, handleBlur: () => () => {},
    handleSubmit: () => {}, submitForm: () => {}, resetForm: () => {},
    getFieldProps: () => ({ value: '', onChange: () => {}, onBlur: () => {}, name: '' }),
    getFieldMeta: () => ({ value: undefined, error: undefined, touched: false }),
    getFieldHelpers: () => ({ setValue: () => {}, setTouched: () => {}, setError: () => {} }),
  };

  const useField = (nameOrConfig) => {
    const name = typeof nameOrConfig === 'string' ? nameOrConfig : (nameOrConfig?.name ?? '');
    const ctx = useFormikContext();
    const field = {
      value: ctx.values?.[name] ?? '',
      onChange: (v) => ctx.setFieldValue?.(name, v),
      onBlur: () => ctx.setFieldTouched?.(name, true),
      name,
    };
    const meta = {
      value: ctx.values?.[name],
      error: ctx.errors?.[name],
      touched: !!ctx.touched?.[name],
      initialValue: ctx.initialValues?.[name],
    };
    const helpers = {
      setValue: (v) => ctx.setFieldValue?.(name, v),
      setTouched: (t) => ctx.setFieldTouched?.(name, t),
      setError: (m) => ctx.setFieldError?.(name, m),
    };
    return [field, meta, helpers];
  };

  return {
    Formik,
    Form: ({ children }) => React.createElement(React.Fragment, null, children),
    Field: ({ name, children }) => {
      const ctx = useFormikContext();
      const field = {
        value: ctx.values?.[name] ?? '',
        onChange: () => {},
        onBlur: () => {},
        name,
      };
      const meta = { value: ctx.values?.[name], error: ctx.errors?.[name], touched: !!ctx.touched?.[name] };
      return typeof children === 'function' ? children({ field, meta, form: ctx }) : null;
    },
    useFormikContext,
    useField,
    // Re-expose internals so ASForm mock can reach the same Formik.
    __FormikContext: FormikContext,
    // Last-rendered bag, for validation tests that call submitForm() directly.
    __getLastFormikBag: () => formikBagRegistry[formikBagRegistry.length - 1],
    __clearFormikRegistry: () => {
      formikBagRegistry.length = 0;
    },
  };
});

// eslint-disable-next-line @typescript-eslint/no-var-requires
const formikMod: any = require('formik');
export const getLastFormikBag = (): any => formikMod.__getLastFormikBag?.();

// Form-prefill helper used by every workflow-press test. Sets all fields
// and waits for Formik's auto-validation to settle so isValid/dirty are
// true before the test asserts on a submit-gated handler. Extracted here
// so the same scaffold isn't repeated inline in every test body.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { waitFor: _waitFor, fireEvent: _fireEvent } = require('@testing-library/react-native');
export async function prefillForm(values: Record<string, unknown>): Promise<void> {
  const bag = getLastFormikBag();
  expect(bag).toBeTruthy();
  await bag.setValues(values);
  await _waitFor(() => {
    const b = getLastFormikBag();
    expect(b?.isValid && b?.dirty).toBe(true);
  });
}

// Helper: press a button and assert the workflow mock was NOT called —
// used for submit-gate tests where the form is left empty so the handler
// should bail out before invoking the workflow.
interface PressOpts {
  screen: { queryAllByTestId: (id: string) => any[] };
  buttonTestId: string;
  workflowMock: jest.Mock;
}
export async function pressAndAssertWorkflowBlocked(opts: PressOpts): Promise<void> {
  await _waitFor(() => {
    const b = getLastFormikBag();
    expect(b?.isValid).toBe(false);
  });
  const [target] = opts.screen.queryAllByTestId(opts.buttonTestId);
  expect(target).toBeTruthy();
  _fireEvent.press(target);
  // Give any async handler a tick to fire; assert it did NOT.
  await new Promise((r) => setTimeout(r, 0));
  expect(opts.workflowMock).not.toHaveBeenCalled();
}

// Helper: press a button after mocking the workflow to reject, assert
// the workflow was called and the handler swallowed the error. Silences
// the dev-mode `if (__DEV__) console.error(...)` the generated handler
// logs so test output stays clean.
interface PressErrorOpts extends PressOpts {
  errorMessage?: string;
}
export async function pressAndAssertWorkflowError(opts: PressErrorOpts): Promise<void> {
  const [target] = opts.screen.queryAllByTestId(opts.buttonTestId);
  expect(target).toBeTruthy();
  opts.workflowMock.mockRejectedValueOnce(new Error(opts.errorMessage ?? 'boom'));
  const origConsoleError = console.error;
  console.error = () => {};
  try {
    _fireEvent.press(target);
    await _waitFor(() => {
      expect(opts.workflowMock).toHaveBeenCalled();
    });
  } finally {
    console.error = origConsoleError;
  }
}

// --- react-native-safe-area-context -------------------------------------------
// ASContainer and friends call useSafeAreaInsets()/useSafeAreaFrame().
// @react-navigation/bottom-tabs also imports SafeAreaInsetsContext and
// SafeAreaFrameContext directly (not just the hook surface) — both must
// be real React contexts or `.Consumer` access throws.
jest.mock('react-native-safe-area-context', () => {
  const React = require('react');
  const inset = { top: 0, right: 0, bottom: 0, left: 0 };
  const frame = { x: 0, y: 0, width: 0, height: 0 };
  const SafeAreaInsetsContext = React.createContext(inset);
  const SafeAreaFrameContext = React.createContext(frame);
  return {
    SafeAreaProvider: ({ children }) =>
      React.createElement(React.Fragment, null, children),
    SafeAreaConsumer: ({ children }) =>
      typeof children === 'function' ? children(inset) : null,
    SafeAreaView: ({ children, ...props }) =>
      React.createElement(require('react-native').View, props, children),
    SafeAreaInsetsContext,
    SafeAreaFrameContext,
    useSafeAreaInsets: () => inset,
    useSafeAreaFrame: () => frame,
    initialWindowMetrics: { insets: inset, frame },
  };
});

// --- react-native-linear-gradient ---------------------------------------------
// ASBottomTabNavigator, ASContainer (gradient backgrounds), and a few other
// components pull in LinearGradient. Stub to a passthrough View so they render.
jest.mock('react-native-linear-gradient', () => {
  const React = require('react');
  const RN = require('react-native');
  const LinearGradient = ({ children, ...props }) =>
    React.createElement(RN.View, props, children);
  return { __esModule: true, default: LinearGradient, LinearGradient };
});

// --- react-native-svg ---------------------------------------------------------
// Components using SVG primitives (ASBottomTabNavigator shape rendering, icon
// libs) need every primitive resolvable. Returns a passthrough View for any
// requested export so `import Svg, { Path, Defs, ... } from 'react-native-svg'`
// always resolves to a renderable component.
jest.mock('react-native-svg', () => {
  const React = require('react');
  const RN = require('react-native');
  const passthrough = (name) => {
    const C = ({ children, ...props }) =>
      React.createElement(RN.View, props, children);
    C.displayName = name;
    return C;
  };
  const handler = {
    get: (_t, prop) => {
      if (prop === '__esModule') return true;
      if (prop === 'default') return passthrough('Svg');
      if (typeof prop === 'symbol') return undefined;
      return passthrough(String(prop));
    },
  };
  return new Proxy({}, handler);
});

// react-native-config — RN 0.85+ ships a codegen native module that
// reads its value at module load via `NativeConfigModule.getConfig()`.
// In tests the native bridge is null; mock both surfaces so any
// `import config from 'react-native-config'` at module scope resolves
// to an empty object instead of crashing.
jest.mock('react-native-config', () => ({ __esModule: true, default: {}, Config: {} }));

// react-native-keychain — default benign mock so auth contexts and any
// module that touches secureStorage at load time have a working Keychain
// API. secureStorage.test.ts re-mocks per-test.
jest.mock('react-native-keychain', () => ({
  setGenericPassword: jest.fn(() => Promise.resolve(true)),
  getGenericPassword: jest.fn(() => Promise.resolve(false)),
  resetGenericPassword: jest.fn(() => Promise.resolve(true)),
  ACCESS_CONTROL: {},
  ACCESSIBLE: {},
  AUTHENTICATION_TYPE: {},
  STORAGE_TYPE: {},
  SECURITY_LEVEL: {},
  BIOMETRY_TYPE: {},
}));

// Auto-mock list for every generated service module lives in its own
// generated file so this setup stays stable across regenerations. The
// side-effect import runs the (jest-hoisted) `jest.mock(...)` registrations
// before any test imports a real service module.
import './generated/service-mocks';

beforeEach(() => {
  mockNavigate.mockClear();
  mockGoBack.mockClear();
  mockReplace.mockClear();
  mockReset.mockClear();
});
