// Auto-generated by app-studio-generator.
//
// FontContext test — verifies the throw-outside-provider guard.

import React from 'react';
import { renderHook } from '@testing-library/react-native';
import {
  FontContextProvider,
  useFontContext,
} from '@real/context/FontContext';

describe('FontContext', () => {
  it('useFontContext() throws when called outside FontContextProvider', () => {
    const origConsoleError = console.error;
    console.error = () => {};
    try {
      expect(() => renderHook(() => useFontContext())).toThrow(
        /must be used within a FontContextProvider/,
      );
    } finally {
      console.error = origConsoleError;
    }
  });

  it('useFontContext() returns the context object when wrapped in a provider', () => {
    const wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
      <FontContextProvider>{children}</FontContextProvider>
    );
    const { result } = renderHook(() => useFontContext(), { wrapper });
    expect(result.current).toBeDefined();
    expect(typeof result.current).toBe('object');
  });
});
