// Auto-generated by app-studio-generator.
//
// GlobalContext test — covers setGlobalData / clearGlobalData /
// removeGlobalDataByKey + the outside-provider guard.

import React from 'react';
import { renderHook, act } from '@testing-library/react-native';
import {
  GlobalContextProvider,
  useGlobalContext,
} from '@real/context/GlobalContext';

const wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <GlobalContextProvider>{children}</GlobalContextProvider>
);

describe('GlobalContext', () => {
  it('useGlobalContext() throws when called outside GlobalContextProvider', () => {
    const origConsoleError = console.error;
    console.error = () => {};
    try {
      expect(() => renderHook(() => useGlobalContext())).toThrow(
        /must be used within a GlobalContextProvider/,
      );
    } finally {
      console.error = origConsoleError;
    }
  });

  it('initial state — globalData is the default fixture and all mutators are functions', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    expect(typeof result.current.setGlobalData).toBe('function');
    expect(typeof result.current.clearGlobalData).toBe('function');
    expect(typeof result.current.removeGlobalDataByKey).toBe('function');
    expect(result.current.globalData).toBeDefined();
    // Accept both empty and seeded defaults — mutator tests below
    // verify behaviour regardless of the initial state.
    expect(typeof result.current.globalData).toBe('object');
    expect(Array.isArray(result.current.globalData)).toBe(false);
  });

  it('setGlobalData merges into the existing globalData', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    const initialKeys = Object.keys(result.current.globalData);
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.setGlobalData({ __test_inserted_key: 'hello' });
    });
    expect((result.current.globalData as Record<string, unknown>).__test_inserted_key).toBe(
      'hello',
    );
    // Existing keys preserved.
    initialKeys.forEach(k => {
      expect(result.current.globalData).toHaveProperty(k);
    });
  });

  it('setGlobalData overwrites the value when the key already exists', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.setGlobalData({ overwriteKey: 'first' });
    });
    expect((result.current.globalData as Record<string, unknown>).overwriteKey).toBe('first');
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.setGlobalData({ overwriteKey: 'second' });
    });
    expect((result.current.globalData as Record<string, unknown>).overwriteKey).toBe(
      'second',
    );
  });

  it('clearGlobalData empties the globalData object', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.clearGlobalData();
    });
    expect(result.current.globalData).toEqual({});
  });

  it('removeGlobalDataByKey deletes the specified key only', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.setGlobalData({ keepMe: 'a', removeMe: 'b' });
    });
    expect((result.current.globalData as Record<string, unknown>).removeMe).toBe('b');
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.removeGlobalDataByKey('removeMe');
    });
    expect((result.current.globalData as Record<string, unknown>).removeMe).toBeUndefined();
    expect((result.current.globalData as Record<string, unknown>).keepMe).toBe('a');
  });

  it('removeGlobalDataByKey is a no-op for a key that does not exist', () => {
    const { result } = renderHook(() => useGlobalContext(), { wrapper });
    const before = { ...result.current.globalData };
    act(() => { // NOSONAR (typescript:S1874) — act() is the documented RTL state-update wrapper
      result.current.removeGlobalDataByKey('__does_not_exist');
    });
    expect(result.current.globalData).toEqual(before);
  });
});
