// Auto-generated by app-studio-generator.
//
// ThemeContext test — token exports, defaultTheme + overrides,
// createThemeData deep-merge, getToken dot-path lookup, provider
// render, and every useThemeX hook.
//
// `tokenTypes` is sourced from the generated ThemeContext.tsx (which was
// built from SDK-discovered tokens), so this test stays in lock-step with
// the runtime context shape per app — no hardcoded category list.

import React from 'react';
import { render, renderHook } from '@testing-library/react-native';
import { Text } from 'react-native';
import {
  themeDefaultValue,
  defaultTheme,
  createThemeData,
  ThemeProvider,
  ThemeContext,
  useThemeComponent,
  useThemeRadius,
  useThemeColors,
  useThemeSpace,
  useThemeBorder,
  useThemeTypography,
  useThemeText,
  useThemeEffect,
  useThemeToken,
} from '@real/context/ThemeContext';

const TOKEN_CATEGORIES = ["component","radius","color","space","border","typography","text","effect","colors"];

// Shared `[hookName, hookRunner]` table — referenced by both the
// "without provider" and "within provider" describe blocks so the table
// isn't emitted twice (SonarQube duplicate-code).
const THEME_HOOK_CASES: Array<[string, () => unknown]> = [
  ['useThemeComponent', () => useThemeComponent()],
  ['useThemeRadius', () => useThemeRadius()],
  ['useThemeColors', () => useThemeColors()],
  ['useThemeSpace', () => useThemeSpace()],
  ['useThemeBorder', () => useThemeBorder()],
  ['useThemeTypography', () => useThemeTypography()],
  ['useThemeText', () => useThemeText()],
  ['useThemeEffect', () => useThemeEffect()],
];

describe('ThemeContext — themeDefaultValue', () => {
  it('exposes every token category + getToken', () => {
    expect(themeDefaultValue).toBeDefined();
    TOKEN_CATEGORIES.forEach((key) => {
      expect(themeDefaultValue).toHaveProperty(key);
    });
    expect(typeof themeDefaultValue.getToken).toBe('function');
  });
});

describe('ThemeContext — defaultTheme', () => {
  it('returns the full token set when called with no overrides', () => {
    const theme = defaultTheme();
    TOKEN_CATEGORIES.forEach((key) => {
      expect(theme).toHaveProperty(key);
    });
    expect(typeof theme.getToken).toBe('function');
  });

  it('substitutes the override for any provided token', () => {
    const customColor = { __mark: 'custom-color-token' } as any;
    const theme = defaultTheme({ color: customColor });
    expect(theme.color).toBe(customColor);
    // The `colors` alias also picks up the override.
    expect(theme.colors).toBe(customColor);
  });

  it('keeps non-overridden tokens at their defaults', () => {
    const customComponent = { __mark: 'custom-component' } as any;
    const theme = defaultTheme({ component: customComponent });
    expect(theme.component).toBe(customComponent);
    // Other tokens fall back to defaults — not equal to our custom marker.
    expect(theme.color).not.toBe(customComponent);
  });
});

describe('ThemeContext — createThemeData', () => {
  it('deep-merges a partial theme with defaults', () => {
    const partial = { component: { __mark: 'partial' } } as any;
    const merged = createThemeData(partial);
    // The merged object retains our partial key while the others come
    // from defaults.
    TOKEN_CATEGORIES.forEach((key) => {
      expect(merged).toHaveProperty(key);
    });
  });

  it('always exposes getToken on the merged result', () => {
    const merged = createThemeData({} as any);
    expect(typeof merged.getToken).toBe('function');
  });
});

describe('ThemeContext — getToken via themeDefaultValue', () => {
  it('returns undefined for a path that does not resolve', () => {
    const out = themeDefaultValue.getToken!('does.not.exist');
    expect(out).toBeUndefined();
  });

  it.each(TOKEN_CATEGORIES.filter((k) => k !== 'colors'))(
    'returns a value for the %s token root',
    (key) => {
      // We don't pin the exact value (assets are mocked), but the path
      // should resolve to something other than undefined for known
      // categories at the top level.
      const root = themeDefaultValue.getToken!(key);
      expect(root).toBeDefined();
    },
  );
});

describe('ThemeContext — ThemeProvider renders children', () => {
  it('renders without throwing when given a minimal theme prop', () => {
    expect(() =>
      render(
        <ThemeProvider theme={{} as any}>
          <Text testID="child">child-renders</Text>
        </ThemeProvider>,
      ),
    ).not.toThrow();
  });
});

describe('ThemeContext — useThemeX hooks WITHOUT a provider (use default)', () => {
  // Unlike GlobalContext/FontContext, ThemeContext provides a non-undefined
  // default (`themeDefaultValue`). Hooks called outside the provider get
  // those default tokens — no throw, defined values.
  it.each(THEME_HOOK_CASES)('%s returns the default token', (_, run) => {
    const { result } = renderHook(run);
    expect(result.current).toBeDefined();
  });

  it('useThemeToken returns the default getToken function', () => {
    const { result } = renderHook(() => useThemeToken());
    expect(typeof result.current).toBe('function');
    // dot-path lookup miss should return undefined
    expect(result.current!('does.not.exist')).toBeUndefined();
  });
});

describe('ThemeContext — hooks WITHIN ThemeProvider (exercises provider code path)', () => {
  // KNOWN GENERATOR QUIRK: `useThemeContextValue` is emitted as
  //   const [component] = useState<typeof component>(initial.component ?? component);
  // The destructured `component` shadows the outer import, so the
  // `?? component` fallback evaluates in the TDZ and resolves to
  // undefined. Result: every TOKEN slice returned by the provider is
  // undefined when `initial.<X>` is not set. The `getToken` function
  // (no `useState` wrapping) still works. We assert the observable
  // behavior — render survives, hooks are callable.
  const wrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <ThemeProvider theme={{} as any}>{children}</ThemeProvider>
  );

  it.each(THEME_HOOK_CASES)('%s is callable under the provider without throwing', (_, run) => {
    expect(() => renderHook(run, { wrapper })).not.toThrow();
  });

  it('useThemeToken still works under the provider (no useState wrap)', () => {
    const { result } = renderHook(() => useThemeToken(), { wrapper });
    expect(typeof result.current).toBe('function');
    expect(result.current!('does.not.exist')).toBeUndefined();
  });
});

describe('ThemeContext — context object', () => {
  it('exports ThemeContext as a Context object with a Provider', () => {
    expect(ThemeContext).toBeDefined();
    expect(typeof ThemeContext.Provider).toBe('object');
  });
});
